### PR TITLE
Fix Cosmos nesting problem

### LINKED ISSUE #3126: port: Fix Cosmos nesting problem (#4973)
The changes in [Fix Cosmos nesting problem (#4973)](https://github.com/microsoft/botbuilder-dotnet/pull/4973) may need to be ported to maintain parity with `microsoft/botbuilder-dotnet`.

<blockquote>
Fixes #4755

## Description
Some customers experienced cryptic error messages when using Cosmos. We discovered that deeply nested data was the culprit, so I've added new error messages to help customers who encounter this problem in the future.

## Specific Changes

  - Two new tests have been added to CosmosDbPartitionStorageTests
  - The custom exception type BotStateException has been created
  - CosmosDbPartitionStorage checks the nesting depth when a Cosmos exception is thrown during a write operation

## Testing
Included
</blockquote>

Please review and, if necessary, port the changes.

### PR DESCRIPTION
**Pull request by v-kydela**
Fixes #3126

## Description

Some customers experienced cryptic error messages when using Cosmos. We discovered that deeply nested data was the culprit, so I've added new error messages to help customers who encounter this problem in the future.

## Specific Changes

  - Two new tests have been added to cosmosDbPartitionedStorage.test.js
  - CosmosDbPartitionedStorage checks the nesting depth when a Cosmos exception is thrown during a write operation
  - Some code cleanup has been applied to cosmosDbPartitionedStorage.ts and cosmosDbPartitionedStorage.test.js

## Testing

Included. Note that waterfall dialogs break recorded tests by generating random instance ID's, and mockHelper.js is designed to fix the test data by looking for waterfall dialogs in the root dialog stack. It is not designed to look for waterfall dialogs inside component dialogs, so it cannot automatically fix the recorded test data for the dialog nesting test. Rather than fixing mockHelper.js or trying some type of non-waterfall dialog, I decided to edit the test data manually because I am told we will be moving to a new testing system soon. This was the simplest solution, but it means that it will need to be manually edited again if new test data is recorded for the dialog nesting test.

### CODE REVIEW

File: libraries/botbuilder-azure/src/cosmosDbPartitionedStorage.ts [hunk 1]
```diff
@@ -229,41 +242,76 @@ export class CosmosDbPartitionedStorage implements Storage {
...
+                        'Try reworking your dialog code to make sure it does not keep dialogs on the stack ' +
+                        "that it's not using. For example, consider using ReplaceDialogAsync instead of BeginDialogAsync."
+                    );
+                } else {
+                    return `${message} Please check your data for signs of unintended recursion.`;
+                }
+            } else if (obj && typeof (obj) === "object") {
+                depth++;
+                return Object.entries(obj).reduce(
+                    (result, entry) => result ?? checkDepth(
```
Comment (joshgummersall) [inline libraries/botbuilder-azure/src/cosmosDbPartitionedStorage.ts:298]: When using `Object.entries`, I think destructuring the entry param via `[key, value]` is more readable than doing `entry[0]` or `entry[1]`.

File: libraries/botbuilder-azure/src/cosmosDbPartitionedStorage.ts [hunk 2]
```diff
@@ -229,41 +242,76 @@ export class CosmosDbPartitionedStorage implements Storage {
...
+                    return (
+                        `${message} This is most likely caused by recursive component dialogs. ` +
+                        'Try reworking your dialog code to make sure it does not keep dialogs on the stack ' +
+                        "that it's not using. For example, consider using ReplaceDialogAsync instead of BeginDialogAsync."
+                    );
+                } else {
+                    return `${message} Please check your data for signs of unintended recursion.`;
+                }
+            } else if (obj && typeof (obj) === "object") {
+                depth++;
```
Comment (joshgummersall) [inline libraries/botbuilder-azure/src/cosmosDbPartitionedStorage.ts:296]: I prefer to keep the state mutation in recursive functions purely in the argument list of the recursive invocation - i.e., `checkDepth(..., depth + 1, ...)` rather than manipulating the value directly. It makes it easier to see all the recursive state changes in one place.

File: libraries/botbuilder-azure/src/cosmosDbPartitionedStorage.ts [hunk 3]
```diff
@@ -229,41 +242,76 @@ export class CosmosDbPartitionedStorage implements Storage {
...
+                return Object.entries(obj).reduce(
+                    (result, entry) => result ?? checkDepth(
+                        entry[1],
+                        depth,
+                        entry[0] === 'dialogStack' ? true : isInDialogState),
```
Comment (joshgummersall) [inline libraries/botbuilder-azure/src/cosmosDbPartitionedStorage.ts:301]: Can be simplified to `entry[0] === 'dialogStack' || isInDialogState`

File: libraries/botbuilder-azure/src/cosmosDbPartitionedStorage.ts [hunk 4]
```diff
@@ -229,41 +242,76 @@ export class CosmosDbPartitionedStorage implements Storage {
...
+                        `${message} This is most likely caused by recursive component dialogs. ` +
+                        'Try reworking your dialog code to make sure it does not keep dialogs on the stack ' +
+                        "that it's not using. For example, consider using ReplaceDialogAsync instead of BeginDialogAsync."
+                    );
+                } else {
+                    return `${message} Please check your data for signs of unintended recursion.`;
+                }
+            } else if (obj && typeof (obj) === "object") {
+                depth++;
+                return Object.entries(obj).reduce(
```
Comment (joshgummersall) [inline libraries/botbuilder-azure/src/cosmosDbPartitionedStorage.ts:297]: I'd write this using `find` instead of `reduce`. I think it's simpler to understand, and iteration will stop as soon as there is an error case.

Comment (joshgummersall) [reply libraries/botbuilder-azure/src/cosmosDbPartitionedStorage.ts:297]: https://www.typescriptlang.org/play?#code/MYewdgzgLgBAtgQwB4BECmAHKALAggG3xAHc0ATGAXhgEYBuAKAdElmGzWAGt0tsqYAChAAjAFYAuGAFcwXMCTAAaGGUw4pYaXBFoATioCWEAJJgUhhEQDmAZSgIoaKSJAh8aBGACUU6HsMwaxgAHxkwNQAzQPIqAD4YAG8GGFSYQ0ihNT4YBMRUdTxCEnJvJJS0ypZoeDQICARrNAEAAwBZZEM4bRgwOqhA4OycGBBMgBJE-N4cAiJSMgBfGDQkYDRycgA6FsYKytSMoWMzCysQOwcnMuSDu5g9NChpPTAhffu7lsm4Ooam5YAFWwxnSEHgIBq+EMXDQ+AAnjBgAhpBBYiJEY9gC8IIYAG7NUBwDDgNBgWBkSw2CBbGAtGAAag+n0qAHJAXpMWhiCA9FxBjB4SAXqoqRckSA1DAoCB4AhYTAIC9moYKSA6r0QLBYZhRedrODwNKOIqHNwYKzGcyWakAEQ4RzpKCs8EKWCowa0gBivJWSAQxI8KmqhjUehkuKCMAASph8Ah1mcbLgIPCwMB0qxPBQxjAAEJoayBJMXFNp4BbW3Wu7eRifZZwtHlG2pR7PV50n5-RpoZYABQ8CCb7E4XEFwvDZEcCBgkV9uOskFGmVkgScEViWJxhnAOzr90WHwb+CbR2E4hgADJL9L4Rg0Lnz2IypRXzBbaIxJwoLabtWJawMAANqwvCKh4lY0hoAAugIADy4jflsZJQAEdRPt4WzRBEgj-pUgggWgYEwBB+BQdBL4JCO3AzNguEtgcpFQUoeH3MM-AMrQLEMZUoFUG+rKUvq9gJlwlohGEJzmGKlyOGg3hlAA-IpwHQXsnxti8bxMWg+6pIeHyaR2shRDEZCMIsezVO4aBbDYgjUTwhSCIkc4gFIiQiAgegeV5ABeUgAAyLCFKiBSokRWGiClAA

**Review by joshgummersall — CHANGES_REQUESTED** [review]

File: libraries/botbuilder-azure/src/cosmosDbPartitionedStorage.ts (hunk 2 above)
Comment (v-kydela) [reply libraries/botbuilder-azure/src/cosmosDbPartitionedStorage.ts:296]: I was thinking in terms of reducing the amount of times the calculation takes place, but your preference makes sense too

File: libraries/botbuilder-azure/src/cosmosDbPartitionedStorage.ts (hunk 4 above)
Comment (joshgummersall) [reply libraries/botbuilder-azure/src/cosmosDbPartitionedStorage.ts:297]: EDIT: `reduce` makes more sense as we want the results of the recursive function, not the offending object. My mistake!

File: libraries/botbuilder-azure/src/cosmosDbPartitionedStorage.ts [hunk 5]
```diff
@@ -353,22 +371,48 @@ export class CosmosDbPartitionedStorage implements Storage {
...
-    /**
-     * The Cosmos JS SDK doesn't return very descriptive errors and not all errors contain a body.
-     * This provides more detailed errors and err['message'] prevents ReferenceError
-     */
-    private throwInformativeError(prependedMessage: string, err: Error | object | string): void {
+    // Return an informative error message if upsert failed due to deeply nested data
+    private checkForNestingError(json: object, err: Error | Record<'message', string> | string): void {
+        const checkDepth = (obj: unknown, depth: number, isInDialogState: boolean): void => {
+            if (depth > maxDepthAllowed) {
+                var message: string = `Maximum nesting depth of ${maxDepthAllowed} exceeded.`;
```
Comment (joshgummersall) [inline libraries/botbuilder-azure/src/cosmosDbPartitionedStorage.ts:382]: `let` preferred to `var`.

**Review by joshgummersall — APPROVED** [review]

**Comment by joshgummersall** [comment]
@v-kydela I accidentally approved & merged before you had a chance to amend the `var` usage. Feel free to submit a quick PR to fix that, or I'll get to it later on. Thanks, and apologies for the early merge.
