### PR TITLE
port: Change ChoiceSet to support LG

### LINKED ISSUE #3393: port: Change ChoiceSet to support LG (#5309)
The changes in [Change ChoiceSet to support LG (#5309)](https://github.com/microsoft/botbuilder-dotnet/pull/5309) may need to be ported to maintain parity with `microsoft/botbuilder-dotnet`.

<blockquote>
Fixes #

## Description
Change ChoiceSet to be able to be defined with LG.

You can define ChoiceSet as 
```
STRING   ==> opt1 | opt2 | opt3
STRING[] ==>  [ "opt1", "opt2", "opt3" ]
CHOICE[] ==> [ { ...opt1..}, {...opt2}, {...opt3...}] 
```

So with LG you can simply do the same:
```
# MyChoices_simple
- dog | cat
```

Or define objects in LG like this
```
# MyChoices_complex
  - '''
  [
    { "value": "dog", "synonyms": ["doggy","wolf"]  },
    { "value": "cat", "synonyms": ["pussycat","kitty"] }
  ]
   '''
```

So a full example:

```
# MyChoices_Prompt
- Please select

# MyChoices_UnknownPrompt
- Not a dog or cat. Please select

# MyChoices_simple
- dog | cat
```
ChoiceInput in a dialog
```json
{
    "$kind": "Microsoft.ChoiceInput",
    "choices": "${MyChoices_simple()}",
    "prompt": "${MyChoices_Prompt()}",
    "unrecognizedPrompt": "${MyChoices_UnknownPrompt()}"
},
```

## Specific Changes
  - Implemented ITemplate<ChoiceSet>.BindData method
  - Changed ChoiceInput and ConfirmInput to use ITemplate<ChoiceSet>.BindData()
  - Fixed Try method to not throw when Expression.Parse() fails.

## Testing
* Added unit tests for simple/complex binding for both ConfirmInput and ChoiceInput with multi-lingual fall back working.
*
</blockquote>

Please review and, if necessary, port the changes.

### PR DESCRIPTION
**Pull request by Danieladu**
Fixes #3393

### CODE REVIEW

File: libraries/botbuilder-dialogs-adaptive/src/input/inputDialog.ts [hunk 1]
```diff
@@ -319,8 +319,8 @@ export abstract class InputDialog extends Dialog implements InputDialogConfigura
      * @param dc The [DialogContext](xref:botbuilder-dialogs.DialogContext) for the current turn of conversation.
      * @param options Initial information to pass to the dialog.
      */
-    protected onInitializeOptions(dc: DialogContext, options: any): any {
-        return Object.assign({}, options);
+    protected async onInitializeOptions(dc: DialogContext, options: any): Promise<any> {
```
Comment (joshgummersall) [inline libraries/botbuilder-dialogs-adaptive/src/input/inputDialog.ts:322]: Shouldn't need `async` as this function already returns a Promise.

File: libraries/botbuilder-dialogs-adaptive/src/input/confirmInput.ts [hunk 2]
```diff
@@ -218,4 +216,26 @@ export class ConfirmInput extends InputDialog implements ConfirmInputConfigurati
...
+
+    private async getConfirmChoices(dc: DialogContext, defaults: (string | Choice)[]): Promise<ChoiceSet> {
+        let confirmChoices: ChoiceSet;
+        if (this.confirmChoices != null) {
+            if (
+                this.confirmChoices.expressionText != null &&
+                this.confirmChoices.expressionText.trimLeft().startsWith('${')
+            ) {
+                // use TemplateInterface to bind (aka LG)
+                confirmChoices = await new ChoiceSet(this.confirmChoices.expressionText).bind(dc, dc.state);
```
Comment (joshgummersall) [inline libraries/botbuilder-dialogs-adaptive/src/input/confirmInput.ts:228]: AFAIK constructors can't be async, so you shouldn't need `await` here.

File: libraries/botbuilder-dialogs-adaptive/src/input/confirmInput.ts [hunk 3]
```diff
@@ -218,4 +216,26 @@ export class ConfirmInput extends InputDialog implements ConfirmInputConfigurati
 
         return culture;
     }
+
+    private async getConfirmChoices(dc: DialogContext, defaults: (string | Choice)[]): Promise<ChoiceSet> {
```
Comment (joshgummersall) [inline libraries/botbuilder-dialogs-adaptive/src/input/confirmInput.ts:220]: Once you drop the `await` you can remove `async` here as you're returning a Promise already.

File: libraries/botbuilder-dialogs-adaptive/src/input/choiceInput.ts [hunk 4]
```diff
@@ -130,15 +130,14 @@ export class ChoiceInput extends InputDialog implements ChoiceInputConfiguration
...
         if (!(options && options.choices && options.choices.length > 0)) {
             if (!options) {
                 options = { choices: [] };
             }
-            const choices = this.choices.getValue(dc.state);
-            options.choices = choices;
+            options.choices = await this.getChoiceSet(dc);
         }
-        return super.onInitializeOptions(dc, options);
+        return await super.onInitializeOptions(dc, options);
```
Comment (joshgummersall) [inline libraries/botbuilder-dialogs-adaptive/src/input/choiceInput.ts:140]: `return await` is almost never needed, just return `super.onInitializeOptions` directly as it's already a Promise.

File: libraries/botbuilder-dialogs-adaptive/src/input/choiceInput.ts [hunk 5]
```diff
@@ -191,15 +190,14 @@ export class ChoiceInput extends InputDialog implements ChoiceInputConfiguration
...
-
         // Format prompt to send
         const prompt = await super.onRenderPrompt(dc, state);
         const channelId = dc.context.activity.channelId;
         const choiceOptions =
             (this.choiceOptions && this.choiceOptions.getValue(dc.state)) || ChoiceInput.defaultChoiceOptions[locale];
         const style = this.style.getValue(dc.state);
-        return Promise.resolve(this.appendChoices(prompt, channelId, choices, style, choiceOptions));
+        const options = dc.state.getValue(ChoiceInput.OPTIONS_PROPERTY);
+        return Promise.resolve(this.appendChoices(prompt, channelId, options.choices, style, choiceOptions));
```
Comment (joshgummersall) [inline libraries/botbuilder-dialogs-adaptive/src/input/choiceInput.ts:200]: Should not need `Promise.resolve` as this is already an `async` function.

File: libraries/botbuilder-dialogs-adaptive/src/input/choiceInput.ts [hunk 6]
```diff
@@ -209,6 +207,16 @@ export class ChoiceInput extends InputDialog implements ChoiceInputConfiguration
         return `ChoiceInput[${this.prompt && this.prompt.toString()}]`;
     }
 
+    private async getChoiceSet(dc: DialogContext) {
+        if (this.choices.expressionText != null && this.choices.expressionText.trimLeft().startsWith('${')) {
+            // use TemplateInterface to bind (aka LG)
+            return await new ChoiceSet(this.choices.expressionText).bind(dc, dc.state);
```
Comment (joshgummersall) [inline libraries/botbuilder-dialogs-adaptive/src/input/choiceInput.ts:213]: `await` should never be needed with constructors.

File: libraries/botbuilder-dialogs-adaptive/src/input/choiceSet.ts [hunk 7]
```diff
@@ -5,20 +5,25 @@
...
+import { LanguageGenerator } from '../languageGenerator';
+import { languageGeneratorKey } from '../languageGeneratorExtensions';
 
 /**
  * Defines ChoiceSet collection.
  */
-export class ChoiceSet extends Array<Choice>
-{
+export class ChoiceSet extends Array<Choice> implements TemplateInterface<ChoiceSet, DialogStateManager> {
+    private template: string;
```
Comment (joshgummersall) [inline libraries/botbuilder-dialogs-adaptive/src/input/choiceSet.ts:16]: Consider `private readonly` if this isn't reassigned.

**Review by joshgummersall — CHANGES_REQUESTED** [review]

File: libraries/botbuilder-dialogs-adaptive/src/input/confirmInput.ts (hunk 2 above)
Comment (Danieladu) [reply libraries/botbuilder-dialogs-adaptive/src/input/confirmInput.ts:228]: the `await` is wating for the "bind" function. Anyway, it is better to separate them to avoid ambiguity

Comment (Danieladu) [reply libraries/botbuilder-dialogs-adaptive/src/input/confirmInput.ts:228]: The `await` is to wait for the 'bind' function, not for the constructor

File: libraries/botbuilder-dialogs-adaptive/src/input/choiceInput.ts (hunk 4 above)
Comment (Danieladu) [reply libraries/botbuilder-dialogs-adaptive/src/input/choiceInput.ts:140]: But I should get the result of "this.getChoiceSet()" at first. So, there need a "await" to wait for the result.

**Review by joshgummersall — APPROVED** [review]
