### PR TITLE
Use QnAMakerOptions, Telemetry, and logPersonalInformation flag in QnAMakerDialog

### LINKED ISSUE #2779: [PORT] logPersonalInformation flag missing in QnAMakerDialog
## Describe the bug
The class [QnAMakerDialog ](https://github.com/microsoft/botbuilder-js/blob/master/libraries/botbuilder-ai/src/qnaMakerDialog.ts#L63) is missing the **logPersonalInformation** flag which [is present in C#](https://github.com/microsoft/botbuilder-dotnet/blob/main/libraries/Microsoft.Bot.Builder.AI.QnA/Dialogs/QnAMakerDialog.cs#L328). This causes, among other things, issues with telemetry reporting in Power BI.
The flag, in turn, is not being passed by constructor to QnAMaker in the method [getQnAClient](https://github.com/microsoft/botbuilder-js/blob/master/libraries/botbuilder-ai/src/qnaMakerDialog.ts#L417), unlike the [behavior in C#](https://github.com/microsoft/botbuilder-dotnet/blob/main/libraries/Microsoft.Bot.Builder.AI.QnA/Dialogs/QnAMakerDialog.cs#L469).

image

image

## Expected behavior
The class QnAMaker should have parity with C#, and telemetry should be being reported.

## Additional context
- This problem was reported in a comment of issue microsoft/botframework-solutions#3612.
- [This is the PR](https://github.com/microsoft/botbuilder-dotnet/pull/3715) where the **logPersonalInformation** property and other telemetry changes were added in C#

### PR DESCRIPTION
**Pull request by Zerryth**
Fixes #2779

## Description
- `QnAMakerDialog` queries a QnA service with a question by using `QnAMakerDialog.getQnAClient` to create a client to make the HTTP request. This client is an instance  of `QnAMaker` class, which allows you to customize queries by allowing **`QnAMakerOptions`**, **`BotTelemetryClient`**, and use of **`logPersonalInformation`** flag.
- However, `QnAMakerDialog.getQnAClient` does *not* currently pass any of the optional parameters to the created qna client
   - This PR exposes the additional optional parameters.

## Specific Changes
  - Enable ability for `QnAMakerDialog` to grab `logPersonalInformation` value from `.env` by default
  - Call to `QnAMaker.onQnaResults` in `getAnswersRaw` method is actually awaited now 
    - (manual functional testing revealed that no `QnAMessage`s  events in Azure Application Insights at all, because of this bug)
  - dependencies added to botbuilder-ai:
    - dotenv (to access `settings` scope)
    - adaptive-expressions (for use of `BoolExpression`)

## Testing
- Added `QnAMakerDialog` unit tests
   - Modified setup in already-existing tests to allow DialogContext to pass into `.getQnAClient`
   - nock'd responses
- Additionally, manual functional testing by:
   - Using [04.waterfall-or-custom-dialog-with-adaptive](https://github.com/microsoft/BotBuilder-Samples/tree/main/experimental/adaptive-dialog/javascript_nodejs/04.waterfall-or-custom-dialog-with-adaptive) sample
      - Customized by adding `QnAMakerDialog`
      - Hooked in live Application Insights for telemetry 
___
Note: looks like I was working on a stale copy of the SDK, and some others had gone ahead of me and opened adding optional parameters, though without tests verifying that telemetry and logPersonalInformation was actually working--this PR at least polishes those aspects

### CODE REVIEW

File: libraries/botbuilder-ai/src/qnaMakerDialog.ts [hunk 1]
```diff
@@ -115,8 +115,18 @@ export interface QnAMakerDialogConfiguration extends DialogConfiguration {
...
     public static $kind = 'Microsoft.QnAMakerDialog';
+
+    /**
+     * Log personal information flag.
+     *
+     * @remarks
+     * Defauls to a value of `=settings.logPersonalInformation`, which retrieves
+     * `logPersonalInformation` flag from settings.
+     */
+    public logPersonalInformation = new BoolExpression('=settings.logPersonalInformation');
```
Comment (Zerryth) [inline libraries/botbuilder-ai/src/qnaMakerDialog.ts:128]: simply set to `settings.logPersonalInformation`, since `.env`, the default config file we use in our samples, doesn't support complex values unlike as appsetting in dotnet 

.env 
:x:
```
telemetry={ 
   logPersonalInformation:  true
}
```
✔️ 
```
logPersonalInformation=true
```

File: libraries/botbuilder-ai/src/qnaMakerDialog.ts [hunk 2]
```diff
@@ -529,9 +539,17 @@ export class QnAMakerDialog extends WaterfallDialog implements QnAMakerDialogCon
             endpointKey: this.endpointKey.getValue(dc.state),
             host: this.getHost(dc),
         };
-        const options = await this.getQnAMakerOptions(dc);
-        const logPersonalInformation = this.logPersonalInformation && this.logPersonalInformation.getValue(dc.state);
-        return new QnAMaker(endpoint, options, this.telemetryClient, logPersonalInformation);
+
+        const logPersonalInformation = this.logPersonalInformation instanceof BoolExpression ?
+            this.logPersonalInformation.getValue(dc.state)
+            : this.logPersonalInformation
```
Comment (Zerryth) [inline libraries/botbuilder-ai/src/qnaMakerDialog.ts:545]: Needs to allow user to be able to use a regular boolean value instead of only a BoolExpression, since not everybody who uses `QnAMakerDialog` is doing so with adaptive dialogs/DialogManager, which sets the scope of `settings` to pull logpii value

File: libraries/botbuilder-ai/src/qnaMaker.ts [hunk 3]
```diff
@@ -206,7 +206,7 @@ export class QnAMaker implements QnAMakerTelemetryClient {
         }
 
         // Log telemetry
-        this.onQnaResults(queryResult, context, telemetryProperties, telemetryMetrics);
+        await this.onQnaResults(queryResult, context, telemetryProperties, telemetryMetrics);
```
Comment (Zerryth) [inline libraries/botbuilder-ai/src/qnaMaker.ts:209]: We'd need something at the functional test level instead of just unit test, because apparently no QnAMessage events were actually filled/logged into Azure Application Insights, because we were missing `await` here

Tested manually to verify this change works

Comment (joshgummersall) [reply libraries/botbuilder-ai/src/qnaMaker.ts:209]: Does this need to complete prior to the `this.generateAnswerUtils.emitTraceInfo` promise? If not, I'd suggest doing:
```typescript
await Promise.all([first, second]);
```

Comment (joshgummersall) [reply libraries/botbuilder-ai/src/qnaMaker.ts:209]: Also, using Sinon and sandboxing can be a useful way to ensure the proper calls occur. It's not a panacea, but if you mocked a method call that occurs inside the promise that this method returns and then invoke `sandbox.verify()` you can ensure the method was called.

File: libraries/botbuilder-ai/src/qnaMakerDialog.ts [hunk 4]
```diff
@@ -115,8 +115,18 @@ export interface QnAMakerDialogConfiguration extends DialogConfiguration {
  * It supports knowledge bases that include follow-up prompt and active learning features.
  * The dialog will also present user with appropriate multi-turn prompt or active learning options.
  */
-export class QnAMakerDialog extends WaterfallDialog implements QnAMakerDialogConfiguration {
```
Comment (joshgummersall) [inline libraries/botbuilder-ai/src/qnaMakerDialog.ts:118]: We want to enforce the interface, was this removed intentionally?

File: libraries/botbuilder-ai/tests/qnaMakerDialog.test.js [hunk 5]
```diff
@@ -52,13 +98,159 @@ describe('QnAMakerDialog', function() {
...
     
             ok(noAuthorityClient instanceof QnAMaker);
-            strictEqual(noAuthorityClient.endpoint.knowledgeBaseId,  KB_ID);
-            strictEqual(noAuthorityClient.endpoint.endpointKey, ENDPOINT_KEY);
+            strictEqual(noAuthorityClient.endpoint.knowledgeBaseId,  kbId);
+            strictEqual(noAuthorityClient.endpoint.endpointKey, endpointKey);
             strictEqual(noAuthorityClient.endpoint.host, createHostName(NOT_V5_HOSTNAME));
         });
+        
+        it('should log telemetry that includes question and username if logPersonalInformation is true in env file', async () => {
```
Comment (joshgummersall) [inline libraries/botbuilder-ai/tests/qnaMakerDialog.test.js:110]: Something to consider - Sinon (in my opinion) offers a much more expressive and robust option for registering expectations and mocks. I've been rewriting several tests using this approach. It's handy as you only have to express the things you expect without needing to be as careful about replicating any functionality.

[Here](https://github.com/microsoft/botbuilder-js/pull/2912/files#diff-df984573d25004aa79b9c21819010fb506d47ef2e3bf8b0515006737c082ff32R79) is an example of registering expectations on a method that is eventually invoked by some other class entirely.

If you create a sandbox, all you need to do at the end of the test is to call `sandbox.verify()` to ensure that all the mocks/expectations you registered were called in all the ways you expected.

You don't have to take this approach, but it can be a big productivity boost, so I encourage you to look into it.

File: libraries/botbuilder-ai/tests/qnaMakerDialog.test.js [hunk 6]
```diff
@@ -1,12 +1,55 @@
...
-const KB_ID = 'kbId';
-const ENDPOINT_KEY = 'endpointKey';
 
 describe('QnAMakerDialog', function() {
-    this.timeout(3000);
+    // this.timeout(3000);
+    this.timeout(120000);
+    const testFiles = fs.readdirSync(`${ __dirname }/TestData/${ this.title }/`);
+
+    beforeEach(function(done){
```
Comment (joshgummersall) [inline libraries/botbuilder-ai/tests/qnaMakerDialog.test.js:26]: `done` is optional and only necessary if you are performing an async operation that isn't compatible with promises.

File: libraries/botbuilder-ai/tests/qnaMakerDialog.test.js [hunk 7]
```diff
@@ -1,12 +1,55 @@
...
+        nock.cleanAll();
+        if (isMockQna) {
+            var fileName = replaceCharacters(this.currentTest.title);
```
Comment (joshgummersall) [inline libraries/botbuilder-ai/tests/qnaMakerDialog.test.js:29]: `const`

File: libraries/botbuilder-ai/tests/qnaMakerDialog.test.js [hunk 8]
```diff
@@ -1,12 +1,55 @@
...
+            var filePath = `${ __dirname }/TestData/${ this.test.parent.title }/`;
+            var arr = testFiles.filter(function(file) { return file.startsWith(fileName + '.')} );
```
Comment (joshgummersall) [inline libraries/botbuilder-ai/tests/qnaMakerDialog.test.js:31]:
```typescript
testFiles.filter((file) => file.startsWith(`${fileName}.`).forEach((file) => {
  ...
})
```

File: libraries/botbuilder-ai/tests/qnaMakerDialog.test.js [hunk 9]
```diff
@@ -1,12 +1,55 @@
...
+        done();
+    })
+    
+    afterEach(function(done){
+        nock.cleanAll();
+        done();
+    });
+    
+    function replaceCharacters (testName, testDesc) {
+        return testName
```
Comment (joshgummersall) [inline libraries/botbuilder-ai/tests/qnaMakerDialog.test.js:49]: Prettier should format this slightly differently.

File: libraries/botbuilder-ai/src/qnaMakerDialog.ts (hunk 2 above)
Comment (joshgummersall) [reply libraries/botbuilder-ai/src/qnaMakerDialog.ts:545]: Prettier formatting should be adding semicolons.

**Review by joshgummersall — CHANGES_REQUESTED** [review]

File: libraries/botbuilder-ai/tests/qnaMakerDialog.test.js (hunk 5 above)
Comment (stevengum) [reply libraries/botbuilder-ai/tests/qnaMakerDialog.test.js:110]: I believe you were already aware of this, but @mdrichardson FYI

File: libraries/botbuilder-ai/src/qnaMakerDialog.ts (hunk 4 above)
Comment (Zerryth) [reply libraries/botbuilder-ai/src/qnaMakerDialog.ts:118]: whoops, definitely not. Conflict resolving fail 🤦

File: libraries/botbuilder-ai/tests/qnaMakerDialog.test.js (hunk 6 above)
Comment (Zerryth) [reply libraries/botbuilder-ai/tests/qnaMakerDialog.test.js]: Done!

...as in removed done :)

File: libraries/botbuilder-ai/tests/qnaMakerDialog.test.js (hunk 8 above)
Comment (Zerryth) [reply libraries/botbuilder-ai/tests/qnaMakerDialog.test.js]: Changed to use fatty arrow and did away with the 1-time use `arr` variable 👍

File: libraries/botbuilder-ai/tests/qnaMakerDialog.test.js (hunk 9 above)
Comment (Zerryth) [reply libraries/botbuilder-ai/tests/qnaMakerDialog.test.js]: Ran prettier 🌷

File: libraries/botbuilder-ai/src/qnaMakerDialog.ts (hunk 2 above)
Comment (Zerryth) [reply libraries/botbuilder-ai/src/qnaMakerDialog.ts]: Ran prettier 🌷

**Review by joshgummersall — APPROVED** [review]

**Review by stevengum — APPROVED** [review]
