### PR TITLE
fix: consistent user-agent handling

### LINKED ISSUE #2082: BotFrameworkAdapter.getClientOptions should ensure requestPolicyFactories includes BB userAgent
## Versions
4.

## Describe the bug
This test will fail due to custom requestPolicyFactories overriding the Bot Builder User-Agent   : https://github.com/microsoft/botbuilder-js/blob/master/libraries/botbuilder/tests/botFrameworkAdapter.test.js#L982 

```js
it(`should still add Botbuilder User-Agent header when custom requestPolicyFactories are provided.`, async function () {
        //ms-rest-js currently adds:
        //botframework-connector/4.0.0 ms-rest-js/0.1.0 Node/v12.14.1 OS/(x64-Windows_NT-10.0.18363)
        //BotBuilder adds BotFrameworkAdapter.USER_AGENT:
        //Microsoft-BotFramework/3.1 BotBuilder/4.1.6 (Node.js,Version=v12.14.1; Windows_NT 10.0.18363; x64)"

        const userAgent = 'Microsoft-BotFramework/3.1 BotBuilder/' + pjson.version + ' (Node.js,Version=' + process.version + '; ' + os.type() + ' ' + os.release() + '; ' + os.arch() + ')';

        nock(reference.serviceUrl)
            .matchHeader('user-agent', val => val.endsWith(userAgent))
            .post('/v3/conversations/convo1/activities/1234')
            .reply(200, {id:'abc123id'});
        
        // This array can be any policies, including a userAgentPolicy
        const factories = [ exponentialRetryPolicy({ value: 'test' }) ]; 
        const adapter = new BotFrameworkAdapter({clientOptions: { requestPolicyFactories: factories } });
            
        await adapter.continueConversation(reference, async turnContext => {
            await turnContext.sendActivity(outgoingMessage);
        });
    });
```

One solution is to splice the requestPolicyFactories array if present, and add a userAgentPolicy factory with BotFrameworkAdapter.USER_AGENT in the appropriate location

image

## To Reproduce
Run the above linked unit test, which is identical to the one above it with only an addition of providing custom requestPolicyFactories

## Expected behavior
BotFrameworkAdapter.USER_AGENT should be present on outgoing ConnectorClient calls, regardless of custom requestPolicyFactories

```   
Microsoft-BotFramework/3.1 BotBuilder/4.1.6 (Node.js,Version=v12.14.1; Windows_NT 10.0.18363; x64)"
```

[bug]

### PR DESCRIPTION
**Pull request by joshgummersall**
Fixes #2082

### CODE REVIEW

File: libraries/botbuilder/src/botFrameworkAdapter.ts [hunk 1]
```diff
@@ -1484,28 +1478,50 @@ export class BotFrameworkAdapter
...
             options.httpClient = httpClient;
         }
 
-        options.userAgent = `${USER_AGENT}${options.userAgent || ''}`;
+        const userAgent = typeof options.userAgent === 'function' ? options.userAgent(USER_AGENT) : options.userAgent;
+        const setUserAgent = userAgentPolicy({
+            value: `${USER_AGENT}${userAgent ?? ''}`,
+        });
+
+        // Resolve any user request policy factories, then includes our user agent via a factory policy
```
Comment (stevengum) [inline libraries/botbuilder/src/botFrameworkAdapter.ts:1495]:
```suggestion
        // Resolve any user request policy factories, then include our user agent via a factory policy
```

**Review by stevengum — APPROVED** [review]
:shipit:
