### PR TITLE
remove property name existance check from botstate

### LINKED ISSUE #894: Accessor Semantics enforce incorrect usage patterns
All Versions. 

In [Botstate.ts](https://github.com/Microsoft/botbuilder-js/blob/master/libraries/botbuilder-core/src/botState.ts) there is a problem with how accessors are created:

```ts
   public createProperty<T = any>(name: string): StatePropertyAccessor<T> {
        if (this.properties.has(name)) { throw new Error(`BotState.createProperty(): a property named '${ name }' already exists.`); }
        const prop: BotStatePropertyAccessor<T> = new BotStatePropertyAccessor<T>(this, name);
        this.properties.set(name, prop);

        return prop;
    }
```

The dictionary that's used to gate the accessor creation is not needed. This prevents multiple accessors from being created, and forces bots to use global static accessors. 

This *signifigantly* differs from the C# code, which allows these to be created at-will:
```cs
        public IStatePropertyAccessor<T> CreateProperty<T>(string name)
        {
            if (string.IsNullOrWhiteSpace(name))
            {
                throw new ArgumentNullException(nameof(name));
            }

            return new BotStatePropertyAccessor<T>(this, name);
        }
```

This difference bleeds into the samples in unexpected ways, and has caused @johnataylor to :boom: :boom: :boom:. He's been :pouting_cat: as he tries to get the sidecar worked wrapped up.

### PR DESCRIPTION
**Pull request by johnataylor**
Fixes #894

### CODE REVIEW

File: libraries/botbuilder-core/src/botState.ts [hunk 1]
```diff
@@ -58,10 +54,7 @@ export class BotState implements PropertyManager {
      * @param name Name of the property to add. Must be unique within the set.
```
Comment (cleemullins) [inline libraries/botbuilder-core/src/botState.ts]: Is this comment still true? I don't think so.
