### PR TITLE
Fix locale determination in confirm/choice prompts/inputs

### LINKED ISSUE #2475: ChoiceInput\ConfirmInput shows TypeError: Cannot read property 'getValue' of undefined in Telegram channel
## Versions
bot framework v 4.9.2.
nodejs 12.18.0
botbuilder-dialogs-adaptive@4.9.2-preview
OS - Windows
Channel Telegram

## Describe the bug
I have tried to build an adaptive dialog based on the sample here : https://github.com/microsoft/BotBuilder-Samples/tree/master/experimental/adaptive-dialog/javascript_nodejs/06.todo-bot

ConfirmInput code:

```js
new ConfirmInput().configure({
    property: new StringExpression('turn.addTodo.cancelConfirmation'),
    prompt: new ActivityTemplate('${ConfirmCancellation()}'),
    // Allow interruptions is an expression. So you can write any expression to determine if an interruption should be allowed.
    // In this case, we will disallow interruptions since this is a cancellation confirmation.
    allowInterruptions: new BoolExpression(false),
    // Controls the number of times user is prompted for this input.
    maxTurnCount: new NumberExpression(1),
    // Default value to use if we have hit the MaxTurnCount
    defaultValue: new BoolExpression('=false'),
    // You can refer to properties of this input via %propertyName notation.
    // The default response is sent if we have prompted the user for MaxTurnCount number of times
    // and if a default value is assumed for the property.
    defaultValueResponse: new ActivityTemplate("Sorry, I do not recognize '${this.value}'. I'm going with '${%DefaultValue}' for now to be safe.")
}),
```

ChoiceInput code:

```js
new ChoiceInput().configure({
    id: 'questionID',
    property: new StringExpression('turn.userAnswer'),
    prompt: new ActivityTemplate('${Question()}'),
    style: new EnumExpression(ListStyle.auto),
    choices: new ArrayExpression(this.getChoices(this.taskProperties.choices)),
    alwaysPrompt: new BoolExpression(true),
    unrecognizedPrompt: new ActivityTemplate('${errUseButtons()}'),
    maxTurnCount: new IntExpression(1),
    allowInterruptions: new BoolExpression(true),
    outputFormat: new EnumExpression(ChoiceOutputFormat.index)
}),
```

Everything is working on a WebChat and Emulator, but when I try to use **Telegram** channel, I get the following error :
_[onTurnError] unhandled error: TypeError: Cannot read property 'getValue' of undefined_

## Expected behavior
If I am correct Choices are supported in Telegram channel , so I expect see prompt with choices in Telegram.

[bug]

### PR DESCRIPTION
**Pull request by v-kydela**
Fixes #2475

## Description
While investigating the customer-reported issue, I discovered some related issues that I decided to fix at the same time. While C# and Python were unaffected by the original issue the customer reported, they may need to be updated for parity with the rest of my changes here.

## Specific Changes

- `mapToNearestLanguage` now correctly treats all falsey values as falsey and doesn't try to call `toLowerCase` on null, etc.
- Since `mapToNearestLanguage` no longer throws an exception when passed a null culture code, `ChoicePrompt.determineCulture` no longer falls back to English to avoid passing a null. This avoids redundantly using English as a fallback twice, and it now works in a way that's consistent with `ConfirmPrompt.determineCulture`.
- `ChoicePrompt.determineCulture` now uses `hasOwnProperty` to be consistent with the other three cases.
- Confirm prompts, confirm inputs, and choice inputs now use `PromptCultureModels.English.locale` instead of "en-us" to avoid using a string literal and to be consistent with choice prompts.
- Choice inputs and confirm inputs now have centralized `determineCulture` functions.

## What I did not change

- @cleemullins made a good point that we might want to throw an error instead of defaulting to English. I didn't like that idea at first because it seemed like it would create the same sense of surprise that this customer wanted to avoid, but now I'm considering that it might be better to throw an error after all. I'm biased as an English speaker, and for non-English speakers it might be very surprising to suddenly see English words and grammar in an otherwise-non-English bot, and it might be hard for a developer to figure out why that's happening. An error message could contain everything the dev needs to know to fix it. I left that alone for now since it seems outside of the scope of this fix, but it may warrant further discussion.
- One of the four locales in the fallback chain for choice prompts and inputs is the locale in the `recognizerOptions` property. It's only used as a potential locale when recognizing input and not when rendering the prompt, which makes sense given the name of the property. But for simplicity and consistency and completeness, we might consider changing it so that it's used in both cases.

### CODE REVIEW

File: libraries/botbuilder-dialogs/src/prompts/choicePrompt.ts [hunk 1]
```diff
@@ -119,10 +119,9 @@ export class ChoicePrompt extends Prompt<FoundChoice> {
     }
 
     private determineCulture(activity: Activity, opt: FindChoicesOptions = null): string {
-        const optLocale = opt && opt.locale ? opt.locale : null;
-        let culture = PromptCultureModels.mapToNearestLanguage(activity.locale || optLocale || this.defaultLocale || PromptCultureModels.English.locale);
-        if (!culture || !this.choiceDefaults[culture])
-        {
+        const optLocale: string = opt && opt.locale ? opt.locale : null;
+        let culture: string = PromptCultureModels.mapToNearestLanguage(activity.locale || optLocale || this.defaultLocale);
+        if (!culture || !this.choiceDefaults.hasOwnProperty(culture)) {
```
Comment (stevengum) [inline libraries/botbuilder-dialogs/src/prompts/choicePrompt.ts:124]: Your changes make sense (thank you for removing the default `PromptCultureModels.English.locale` value).

However, this function in the larger context doesn't make sense to me. Could you walk me through it?

In [ChoicePrompt.onRecognize](https://github.com/microsoft/botbuilder-js/blob/499790d51a0d1567c06a9b38e883ef5134b68c48/libraries/botbuilder-dialogs/src/prompts/choicePrompt.ts#L111) determineCulture is called and overrides any pre-existing values on `this.recognizerOptions`. Aren't there concurrency issues if either `this.choiceDefaults` or `this.recognizerOptions` changes?

(`this.choiceDefaults` is potentially a pointer to a public object and `this.recognizerOptions` is a public property)

In [ChoicePrompt.onPrompt](https://github.com/microsoft/botbuilder-js/blob/499790d51a0d1567c06a9b38e883ef5134b68c48/libraries/botbuilder-dialogs/src/prompts/choicePrompt.ts#L86) the locale is obtained without it always being used. 

If `this.choiceOptions || this.choiceDefaults[PromptCultureModels.English.locale]` resolve to undefined, this is fine because [ChoiceFactory provides default values instead](https://github.com/microsoft/botbuilder-js/blob/499790d51a0d1567c06a9b38e883ef5134b68c48/libraries/botbuilder-dialogs/src/choices/choiceFactory.ts#L167-L173)?

It seems like there are some redundancies going on, so any insight (and test coverage) would be helpful at clearing things up

File: libraries/botbuilder-dialogs-adaptive/src/input/choiceInput.ts [hunk 2]
```diff
@@ -136,4 +132,16 @@ export class ChoiceInput extends InputDialog {
         return `ChoiceInput[${ this.prompt && this.prompt.toString() }]`;
     }
 
+    private determineCulture(dc: DialogContext, opt: FindChoicesOptions = null): string {
+        const optLocale: string = opt && opt.locale ? opt.locale : null;
+        let culture: string = PromptCultureModels.mapToNearestLanguage(
+            dc.context.activity.locale ||
+            optLocale ||
+            (this.defaultLocale && this.defaultLocale.getValue(dc.state)));
+        if (!culture || !ChoiceInput.defaultChoiceOptions.hasOwnProperty(culture)) {
```
Comment (stevengum) [inline libraries/botbuilder-dialogs-adaptive/src/input/choiceInput.ts:141]: Can you add a blank line in between?

Comment (stevengum) [reply libraries/botbuilder-dialogs-adaptive/src/input/choiceInput.ts:141]: Do you know why the behavior in "defaultChoices" changed between Prompts and Inputs?

File: libraries/botbuilder-dialogs-adaptive/src/input/choiceInput.ts [hunk 3]
```diff
@@ -136,4 +132,16 @@ export class ChoiceInput extends InputDialog {
         return `ChoiceInput[${ this.prompt && this.prompt.toString() }]`;
     }
 
+    private determineCulture(dc: DialogContext, opt: FindChoicesOptions = null): string {
```
Comment (stevengum) [inline libraries/botbuilder-dialogs-adaptive/src/input/choiceInput.ts:135]: Shouldn't this mirror the C# implementation of [GetCulture()](https://github.com/microsoft/botbuilder-dotnet/blob/46aa02a7875583fed000046f013eeac9f70d41b0/libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Input/ChoiceInput.cs#L194-L206)

Comment (v-kydela) [reply libraries/botbuilder-dialogs-adaptive/src/input/choiceInput.ts:135]: I discuss in the description that I've made changes that, if accepted, may require parity pull requests in other repos. In this case, the C# implementation is flawed because it does not include the `FindChoicesOptions` as a potential fallback. Would you like me to remove everything that doesn't match C# and save those changes for later, or is it okay to make this fixes now?

File: libraries/botbuilder-dialogs-adaptive/src/input/choiceInput.ts (hunk 2 above)
Comment (v-kydela) [reply libraries/botbuilder-dialogs-adaptive/src/input/choiceInput.ts:141]: I'm not sure what you mean by the behavior in defaultChoices or which changes you're referring to. Are you asking why the inputs have fewer fallbacks or why they didn't use `mapToNearestLanguage` or why they lacked `determineCulture` functions? In any case it's pretty perplexing to me that so much functionality was ever duplicated, since it seems like the adaptive dialog code should have been relying on the existing prompts.

File: libraries/botbuilder-dialogs/src/prompts/choicePrompt.ts (hunk 1 above)
Comment (v-kydela) [reply libraries/botbuilder-dialogs/src/prompts/choicePrompt.ts:124]: I think `determineCulture` is just supposed to determine the culture by accounting for potential missing or malformed values and resorting to fallbacks.

`this.choiceDefaults` is private and doesn't change. Sure the object is public like you said, but it would be pretty strange to modify the object passed as choice defaults, and I don't think anything bad would happen even if it does get modified. Like with `this.recognizerOptions`, the worst that could happen is that different settings get used. It's certainly strange that the options locale gets modified in `onRecognize` but if the property was undefined then the new object that's created doesn't get assigned to the property. I guess if the same dialog instance was used by multiple users with different locales then their locales could get passed from one to another, and I guess that's why the options locale is third in the fallback chain.

I can see that in `onPrompt` the locale is obtained without it always being used, and I suspect the author chose clarity over efficiency since `determineCulture` isn't a slow function to run.

Yes, it looks like `ChoiceFactory` provides default values, but that seems a little outside the scope of this PR. The scope has already creeped beyond the customer's issue so I had thought it was more likely that you'd think it was too much than too little. While I was happy to expand the scope, I had still thought this PR should just be about determining the culture. Do you want to also include code about making sure the choice options work properly?

File: libraries/botbuilder-dialogs/src/prompts/promptCultureModels.ts [hunk 4]
```diff
@@ -137,7 +137,7 @@ export class PromptCultureModels {
      * @returns Normalized locale.
      */
     public static mapToNearestLanguage(cultureCode: string): string {
-        if (cultureCode !== undefined) {
+        if (cultureCode) {
```
[the remark this answers is not in the document]
Comment (v-kydela) [reply libraries/botbuilder-dialogs/src/prompts/promptCultureModels.ts:140]: Done

**Comment by carlosscastro** [comment]
Thanks Kyle! I'm doing some similar work in c# with a slightly different approach. Currently C# is not fully Can we not merge this PR until mid next week when I have the C# version? I want to make sure we do the same in both languages.

You mentioned that you proposed language changes for other languages. I'll keep those in mind when I do the C# work.

**Comment by v-kydela** [comment]
@carlosscastro 
@stevengum 

Can either of you comment on what's needed to move forward with this? I don't have permissions for the functional tests check that's failing and I don't know if that's relevant to this PR

File: libraries/botbuilder-dialogs-adaptive/src/input/confirmInput.ts [hunk 5]
```diff
@@ -97,11 +96,7 @@ export class ConfirmInput extends InputDialog {
 
     protected async onRenderPrompt(dc: DialogContext, state: InputState): Promise<Partial<Activity>> {
         // Determine locale
-        let locale: string = dc.context.activity.locale || this.defaultLocale.getValue(dc.state);
-        if (!locale || !ConfirmInput.defaultChoiceOptions.hasOwnProperty(locale)) {
-            locale = 'en-us';
-        }
-        locale = locale.toLowerCase(); // to match format 'en-US'
+        let locale: string = this.determineCulture(dc);
```
Comment (joshgummersall) [inline libraries/botbuilder-dialogs-adaptive/src/input/confirmInput.ts:99]: There are a handful of places in this PR where a `string` type is manually assigned even though the type can be inferred. We should avoid this - let the compiler do as much heavy lifting as it can.

```typescript
let locale = this.determineCulture(dc);
```

File: libraries/botbuilder-dialogs-adaptive/src/input/choiceInput.ts [hunk 6]
```diff
@@ -136,4 +132,17 @@ export class ChoiceInput extends InputDialog {
...
```
Comment (joshgummersall) [inline libraries/botbuilder-dialogs-adaptive/src/input/choiceInput.ts:135]: Why are we defaulting to `null`? It seems unnecessary as the default, even if the parameter is omitted, is `undefined` which is falsey. This happens in a few places that can all be cleaned up.

File: libraries/botbuilder-dialogs-adaptive/src/input/choiceInput.ts [hunk 7]
```diff
@@ -136,4 +132,17 @@ export class ChoiceInput extends InputDialog {
...
+        const optLocale: string = opt && opt.locale ? opt.locale : null;
+        let culture: string = PromptCultureModels.mapToNearestLanguage(
+            dc.context.activity.locale ||
+            optLocale ||
+            (this.defaultLocale && this.defaultLocale.getValue(dc.state)));
+
+        if (!culture || !ChoiceInput.defaultChoiceOptions.hasOwnProperty(culture)) {
```
Comment (joshgummersall) [inline libraries/botbuilder-dialogs-adaptive/src/input/choiceInput.ts:142]: It's a lot easier to read these boolean expressions if they are combined with `&&` and only undergo a single negation.

```typescript
if (!(culture && ChoiceInput.defaultChoiceOptions.hasOwnProperty(culure))) {
  ...
}
```
I see this logic in a few places so please update those as well.

**Review by joshgummersall — CHANGES_REQUESTED** [review]
Once we get these changes addressed I think we can land this PR.

File: libraries/botbuilder-dialogs-adaptive/src/input/choiceInput.ts (hunk 6 above)
Comment (v-kydela) [reply libraries/botbuilder-dialogs-adaptive/src/input/choiceInput.ts:135]: TypeScript is unhappy with omitted parameters unless they have a default value. Removing the default value will result in a TypeScript compiler error. Is it better to pass null as an argument to the function call instead of as a default value?

Comment (joshgummersall) [reply libraries/botbuilder-dialogs-adaptive/src/input/choiceInput.ts:135]: Discussed on Teams that using `?` to mark the parameter as optional will work.

Comment (v-kydela) [reply libraries/botbuilder-dialogs-adaptive/src/input/choiceInput.ts:135]: Never mind, I forgot about `?` syntax

**Comment by joshgummersall** [comment]
@v-kydela couple merge conflicts to resolve as well.

**Review by stevengum — APPROVED** [review]

**Review by joshgummersall — APPROVED** [review]
