### PR TITLE
adjusted override/callback docstrings

### LINKED ISSUE #2897: TeamsActivityHandler <teams event>Event() methods have incorrect doc strings
Per discussion w/ @stevengum, there's two different ways that developers can handle Teams Activities:

1. Use the older callback chaining by passing in callbacks, or
2. Use inheritance and override the methods in `TeamsActivityHandler`

The methods in [`TeamsActivityHandler`](https://github.com/microsoft/botbuilder-js/blob/main/libraries/botbuilder/src/teamsActivityHandler.ts) are *supposed* to fit the following scheme:

* Methods **starting with `handle`** (e.g. `handleTeamsTaskModuleFetch()`) must be overridden by the developer, if the developer wants the bot to handle Invoke activities, and
* Methods **ending with `Event`** (e.g. `onTeamsMembersAddedEvent()`) can be used by passing in callbacks, however
* Methods **starting with `on` and *not* ending in `Event`** (e.g. `onTeamsMembersAdded()`) can be overridden

The code in `TeamsActivityHandler` supports this. However, the [documentation](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-basics-teams?view=azure-bot-service-4.0&tabs=javascript#teams-bot-logic) and the doc strings in the code are wrong. Both of these [suggest that the developer override the `...Event()` methods](https://github.com/microsoft/botbuilder-js/blob/main/libraries/botbuilder/src/teamsActivityHandler.ts#L681):

```js
    /**
     * Override this in a derived class to provide logic for when members other than the bot
     * leave the channel, such as your bot's good-bye logic.
     * @param handler
     * @returns A promise that represents the work queued.
     */
    public onTeamsMembersRemovedEvent(
        handler: (
            membersRemoved: TeamsChannelAccount[],
            teamInfo: TeamInfo,
            context: TurnContext,
            next: () => Promise<void>
        ) => Promise<void>
[...]
```

**To-do:**
- [ ] JS SDK Fix
- [ ] Docs Fix @JonathanFingold: I might submit a docs PR for this, but let me know if you'd prefer to.

### PR DESCRIPTION
**Pull request by mdrichardson**
Fixes #2897 (except for docs)

# I'm not 100% on the verbiage. Suggestions welcome.

## Description
Per discussion w/ @stevengum, there's two different ways that developers can handle Teams Activities:

1. Use the older callback chaining by passing in callbacks, or
2. Use inheritance and override the methods in `TeamsActivityHandler`

The methods in [`TeamsActivityHandler`](https://github.com/microsoft/botbuilder-js/blob/main/libraries/botbuilder/src/teamsActivityHandler.ts) are *supposed* to fit the following scheme:

* Methods **starting with `handle`** (e.g. `handleTeamsTaskModuleFetch()`) must be overridden by the developer, if the developer wants the bot to handle Invoke activities, and
* Methods **ending with `Event`** (e.g. `onTeamsMembersAddedEvent()`) can be used by passing in callbacks, however
* Methods **starting with `on` and *not* ending in `Event`** (e.g. `onTeamsMembersAdded()`) can be overridden

The code in `TeamsActivityHandler` supports this. However, the [documentation](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-basics-teams?view=azure-bot-service-4.0&tabs=javascript#teams-bot-logic) and the doc strings in the code are wrong. Both of these [suggest that the developer override the `...Event()` methods](https://github.com/microsoft/botbuilder-js/blob/main/libraries/botbuilder/src/teamsActivityHandler.ts#L681):

```js
    /**
     * Override this in a derived class to provide logic for when members other than the bot
     * leave the channel, such as your bot's good-bye logic.
     * @param handler
     * @returns A promise that represents the work queued.
     */
    public onTeamsMembersRemovedEvent(
        handler: (
            membersRemoved: TeamsChannelAccount[],
            teamInfo: TeamInfo,
            context: TurnContext,
            next: () => Promise<void>
        ) => Promise<void>
[...]
```

If the developer were to actually override this method, they would be unable to catch `TeamsMembersRemoved`, unless they also happen to override `onTeamsMembersRemoved`

## Specific Changes

- Provided instructions in `TeamsActivityHandler` class docstring for how/when to use each method.
- Shifted around current docstrings to their appropriate place.

### CODE REVIEW

File: libraries/botbuilder/src/teamsActivityHandler.ts [hunk 1]
```diff
@@ -30,6 +29,20 @@ import {
...
 
+/**
+ * Adds support for Microsoft Teams specific events and interactions.
+ * @remarks
+ * Developers may handle activities sent from Microsoft Teams via two methods:
+ *  1. Overriding methods starting with `handle...()` (e.g. `handleTeamsTaskModuleFetch()`) .
+ *      * The only way to handle Invoke activities is to override these methods.
+ *  2. Overriding methods starting with `on..` and *not* ending in `..Event()` (e.g. `onTeamsMembersAdded()`)
+ *  3. Passing callbacks to methods starting with `on..` *and* ending in `...Event()` (e.g. `onTeamsMembersAddedEvent()`),
+ *      to stay in line with older {@link ActivityHandler} implementation, or instead
```
Comment (joshgummersall) [inline libraries/botbuilder/src/teamsActivityHandler.ts:40]: `, or instead` seems like it should be removed.

**Review by joshgummersall — APPROVED** [review]
Looks good, one small suggestion.

File: libraries/botbuilder/src/teamsActivityHandler.ts (hunk 1 above)
Comment (mdrichardson) [reply libraries/botbuilder/src/teamsActivityHandler.ts]: Whoops! I switched around #2 and #3 and forgot to fix that part. Re-pushed with fix/update.
