### PR TITLE
fix: QnaMakerDialog constructor

### LINKED ISSUE #2974: [botbuilder-ai] QnAMakerDialog only recognizes the empty constructor
## Versions
What package version of the SDK are you using.
[botbuilder-ai@4.11.0-rc0](https://botbuilder.myget.org/feed/botbuilder-v4-js-daily/package/npm/botbuilder-ai/4.11.0-rc0)

Also, this will happen in rc1 too.

What nodejs version are you using
[12.18.1](https://nodejs.org/en/blog/release/v12.18.1/)

What browser version are you using
\-

What os are you using
Windows 10

## Describe the bug
[QnAMakerDialog](https://github.com/microsoft/botbuilder-js/blob/main/libraries/botbuilder-ai/src/qnaMakerDialog.ts) only recognizes the empty constructor.

The solution is to overload correctly the constructor like the image. This issue is blocking and can generate inconsistencies in the QnAMakerDialog functionality 

image

## To Reproduce
1. Install [botbuilder-ai@4.11.0-rc0](https://botbuilder.myget.org/feed/botbuilder-v4-js-daily/package/npm/botbuilder-ai/4.11.0-rc0) package
2. Import `QnAMakerDialog` from `botbuilder-ai`
3. Create a new QnAMakerDialog instance
4. Check that it's not possible to use the [constructor](https://github.com/microsoft/botbuilder-js/blob/main/libraries/botbuilder-ai/src/qnaMakerDialog.ts#L198) which contains parameters

## Expected behavior
Use both constructors.

## Screenshots
_QnAMakerDialog only recognizes the empty constructor_
image

## Additional context
We identified that the QnAMakerDialog's [empty constructor](https://github.com/microsoft/botbuilder-js/pull/2235/files#diff-92741b8f9cff6cd634a136136658e9aaa337d9dd70ec50220a8695eed97c5dd4) was added in #2235 causing issues in the overloading of the constructor with parameters

We used as a guide [TypeScript Constructor Overload with Empty Constructor](https://medium.com/codespace69/typescript-constructor-overload-with-empty-constructor-e9cb7f34bf3f) to fix the issue of the QnAMakerDialog constructor.

### PR DESCRIPTION
**Pull request by joshgummersall**
Fixes #2974

### CODE REVIEW

File: libraries/botbuilder-ai/src/qnaMakerDialog.ts [hunk 1]
```diff
@@ -194,7 +194,6 @@ export class QnAMakerDialog extends WaterfallDialog implements QnAMakerDialogCon
      * @param strictFilters (Optional) QnA Maker metadata with which to filter or boost queries to the knowledge base; or null to apply none.
      * @param dialogId (Optional) Id of the created dialog. Default is 'QnAMakerDialog'.
      */
-    public constructor();
     public constructor(
```
Comment (joshgummersall) [inline libraries/botbuilder-ai/src/qnaMakerDialog.ts:197]: Every parameter is optional, so there is no need to explicitly list an overload.

**Review by stevengum — APPROVED** [review]
