### PR TITLE
Scoped services

### LINKED ISSUE #2098: [PORT] Fix for Issue3767 (scoped services not working correctly)
> Port this change from botbuilder-dotnet/master branch:
https://github.com/microsoft/botbuilder-dotnet/pull/3788

* Remove PushPop on turnstate, because it didn't work right
* added scoped Services property to DC.
* set services in CreateChildContext
* Implement Reprompt in way that maintains dialogcontext for AD.
* Moved ITemplate to dialogs (NOTE: This is new for R9, so not breaking change)
* changed ITemplate to be DialogContext based (and default to dc.State for data)

# Changed projects
* Microsoft.Bot.Builder.AI.QnA
* Microsoft.Bot.Builder.Dialogs.Adaptive
* Microsoft.Bot.Builder.Dialogs.Debugging
* Microsoft.Bot.Builder.Dialogs
* Microsoft.Bot.Builder
* Microsoft.Bot.Builder.Dialogs.Adaptive.Templates.Tests
* Microsoft.Bot.Builder.Dialogs.Adaptive.Tests
* Microsoft.Bot.Builder.TestBot.Json
* Microsoft.Bot.Builder.Tests

[Adaptive,R9]

### PR DESCRIPTION
**Pull request by chon219**
Fixes #2098 

## Description

Scoped services property in dialog context.

## Specific Changes

  - Added scoped services property in dialog context
  - Replaced pop/push turn state in adaptive dialog with set scoped services
  - Changed template interface's bind api to be dialog context based
  - Replaced `LanguageGenerationMiddleware` with `useLanguageGeneration` extension to DialogManager to inject language generator/language generator manager into scoped services
  - Added `useResourceExplorer` extension to DialogManager to inject resource explorer into scoped services
  - Added `useLanguagePolicy` extension to DialogManager to inject language policy into scoped services
  - Updated expression properties to avoid parsing expression during setValue() to support LG injection
  - Updated related components to reflect changes above

## Testing

Updated all the test cases to work with the changes.

### CODE REVIEW

File: libraries/adaptive-expressions/src/expressionProperties/enumExpression.ts [hunk 1]
```diff
@@ -20,13 +20,11 @@ export class EnumExpression<T> extends ExpressionProperty<T> {
     }
 
     public setValue(value: T | string | Expression): void {
-        this.value = undefined;
-        this.expression = undefined;
+        super.setValue(undefined);
```
Comment (chrimc62) [inline libraries/adaptive-expressions/src/expressionProperties/enumExpression.ts:23]: Does this inherit documentation from ExpressionProperty<T>?

File: libraries/adaptive-expressions/src/expressionProperties/expressionProperty.ts [hunk 2]
```diff
@@ -13,38 +13,56 @@ import { Expression } from '../expression';
...
 
-    public expression: Expression;
+    /**
+     * Getes or sets the expression text to evaluate to get the value.
+     */
+    public expressionText: string;
 
     public toString(): string {
-        return this.expression ? `=${ this.expression.toString() }` : (this.value ? this.value.toString() : '');
+        if (this.expressionText) {
```
Comment (chrimc62) [inline libraries/adaptive-expressions/src/expressionProperties/expressionProperty.ts:34]: Documentation.  All public classes / methods should have documentation.

File: libraries/botbuilder-dialogs/src/dialogContext.ts [hunk 3]
```diff
@@ -54,6 +54,37 @@ export interface DialogState {
...
  */
 export class DialogContext {
+    /**
+      * Creates an new instance of the [DialogContext](xref:botbuilder-dialogs.DialogContext) class.
+      * 
+      * @remarks
+      * Passing in a dialog context instance will clone the dialog context.
+      * @param dialogs The dialog set for which to create the dialog context.
+      * @param context The context object for the current turn of the bot.
+      * @param state The state object to use to read and write dialog state to storage.
```
Comment (chrimc62) [inline libraries/botbuilder-dialogs/src/dialogContext.ts:64]: Non-existent parameter.

File: libraries/botbuilder-dialogs-adaptive/src/templates/textTemplate.ts [hunk 4]
```diff
@@ -1,6 +1,7 @@
+import { DialogContext } from 'botbuilder-dialogs';
 import { TemplateInterface } from '../template';
```
Comment (chrimc62) [inline libraries/botbuilder-dialogs-adaptive/src/templates/textTemplate.ts:2]: Missing header.

**Comment by chrimc62** [comment]
Main comment is to make sure all public class/method/property have documentation.

File: libraries/botbuilder-dialogs/src/dialogContext.ts (hunk 3 above)
Comment (chon219) [reply libraries/botbuilder-dialogs/src/dialogContext.ts:64]: removed.

File: libraries/adaptive-expressions/src/expressionProperties/enumExpression.ts (hunk 1 above)
Comment (chon219) [reply libraries/adaptive-expressions/src/expressionProperties/enumExpression.ts:27]: added doc.

File: libraries/adaptive-expressions/src/expressionProperties/expressionProperty.ts (hunk 2 above)
Comment (chon219) [reply libraries/adaptive-expressions/src/expressionProperties/expressionProperty.ts:37]: added doc.

File: libraries/botbuilder-dialogs-adaptive/src/templates/textTemplate.ts (hunk 4 above)
Comment (chon219) [reply libraries/botbuilder-dialogs-adaptive/src/templates/textTemplate.ts:10]: added missing header.

File: libraries/botbuilder-dialogs-adaptive/src/languageGeneratorExtensions.ts [hunk 5]
```diff
@@ -13,53 +13,42 @@ import { LanguageGenerator } from './languageGenerator';
...
+    /**
+     * Register default LG file or a language generator as default language generator.
+     */
+    public static useLanguageGeneration(dialogManager: DialogManager, lg?: string | LanguageGenerator): DialogManager {
+        const resourceExplorer: ResourceExplorer = dialogManager.initialTurnState.get(resourceExplorerKey) || new ResourceExplorer();
+        let defaultLg = 'main.lg';
+        if (lg) {
+            if (typeof lg === 'string') {
+                defaultLg = lg;
+            }
```
Comment (stevengum) [inline libraries/botbuilder-dialogs-adaptive/src/languageGeneratorExtensions.ts:30]: Simplify to

```suggestion
        const defaultLg = lg && typeof lg === 'string' ? lg : 'main.lg';
```

Unfortunately both the `lg` truthy and `typeof` checks are required since `typeof` doesn't evaluate if the string is truthy....

Comment (chon219) [reply libraries/botbuilder-dialogs-adaptive/src/languageGeneratorExtensions.ts]: Got it, thanks for your suggestion.

File: libraries/botbuilder-dialogs/src/dialogContext.ts [hunk 6]
```diff
@@ -54,6 +54,37 @@ export interface DialogState {
  * ```
  */
 export class DialogContext {
+    /**
+      * Creates an new instance of the [DialogContext](xref:botbuilder-dialogs.DialogContext) class.
+      * 
+      * @remarks
+      * Passing in a dialog context instance will clone the dialog context.
+      * @param dialogs The dialog set for which to create the dialog context.
+      * @param context The context object for the current turn of the bot.
```
Comment (chrimc62) [inline libraries/botbuilder-dialogs/src/dialogContext.ts:63]: >context [](start = 15, length = 7)

contextOrDC

File: libraries/adaptive-expressions/src/expressionProperties/expressionProperty.ts [hunk 7]
```diff
@@ -67,22 +91,31 @@ export class ExpressionProperty<T> {
...
         if (this.expression) {
             return this.expression.tryEvaluate(data) as any;
         }
 
         return { value: this.value, error: undefined };
     }
 
+    /**
+     * Set the value.
+     * @param value value to set.
```
Comment (chrimc62) [inline libraries/adaptive-expressions/src/expressionProperties/expressionProperty.ts:107]: >value [](start = 20, length = 5)

Value

File: libraries/adaptive-expressions/src/expressionProperties/intExpression.ts [hunk 8]
```diff
@@ -18,6 +18,11 @@ export class IntExpression extends ExpressionProperty<number> {
         super(value, 0);
     }
 
+    /**
+     * try to get the value.
```
Comment (chrimc62) [inline libraries/adaptive-expressions/src/expressionProperties/intExpression.ts:22]: Try

File: libraries/adaptive-expressions/src/expressionProperties/intExpression.ts [hunk 9]
```diff
@@ -18,6 +18,11 @@ export class IntExpression extends ExpressionProperty<number> {
...
+     * @param data data to use for expression binding.
```
Comment (chrimc62) [inline libraries/adaptive-expressions/src/expressionProperties/intExpression.ts:23]: >data [](start = 19, length = 4)

Data

File: libraries/adaptive-expressions/src/expressionProperties/stringExpression.ts [hunk 10]
```diff
@@ -27,34 +27,31 @@ export class StringExpression extends ExpressionProperty<string> {
...
     }
 
-    public tryGetValue(data: object): { value: string; error: Error } {
-        if (typeof this.value == 'string') {
-            let v: any, e: string;
-            const expressionStr = '`' + this.value + '`';
-            ({value: v, error: e} = Expression.parse(expressionStr).tryEvaluate(data));
+    /**
+     * Set a string value.
+     * @param value value to set.
```
Comment (chrimc62) [inline libraries/adaptive-expressions/src/expressionProperties/stringExpression.ts:32]: >value [](start = 20, length = 5)

Value

File: libraries/adaptive-expressions/src/expressionProperties/valueExpression.ts [hunk 11]
```diff
@@ -27,31 +27,24 @@ export class ValueExpression extends ExpressionProperty<any> {
...
-
-            return e == undefined ? { value: v as string, error: undefined } : { value: v as string, error: new Error(e) };
-        }
-
-        return super.tryGetValue(data);
-    }
-    
+    /**
+     * Set value as value expression.
+     * @param value value to set.
```
Comment (chrimc62) [inline libraries/adaptive-expressions/src/expressionProperties/valueExpression.ts:32]: >value [](start = 20, length = 5)

Value

File: libraries/botbuilder-dialogs-adaptive/src/languageGeneratorExtensions.ts [hunk 12]
```diff
@@ -0,0 +1,49 @@
...
+import { LanguageGenerator } from './languageGenerator';
+import { resourceExplorerKey } from './resourceExtensions';
+import { LanguagePolicy } from './languagePolicy';
+
+export const languageGeneratorKey = Symbol('LanguageGenerator');
+export const languageGeneratorManagerKey = Symbol('LanguageGeneratorManager');
+export const languagePolicyKey = Symbol('LanguagePolicy');
+
+export class LanguageGeneratorExtensions {
+    /**
```
Comment (chrimc62) [inline libraries/botbuilder-dialogs-adaptive/src/languageGeneratorExtensions.ts:21]: Documentation.

File: libraries/botbuilder-dialogs-adaptive/src/languageGeneratorExtensions.ts [hunk 13]
```diff
@@ -0,0 +1,49 @@
...
+     * Register default LG file or a language generator as default language generator.
+     */
+    public static useLanguageGeneration(dialogManager: DialogManager, lg?: string | LanguageGenerator): DialogManager {
```
Comment (chrimc62) [inline libraries/botbuilder-dialogs-adaptive/src/languageGeneratorExtensions.ts:24]: >dialogManager: DialogManager, lg?: string | LanguageGenerator [](start = 40, length = 61)

Document parameters.

File: libraries/botbuilder-dialogs-adaptive/src/languageResourceLoader.ts [hunk 14]
```diff
@@ -14,9 +14,9 @@ import { IResource, ResourceExplorer } from 'botbuilder-dialogs-declarative';
 import { LanguagePolicy } from  './languagePolicy';
 
 export class LanguageResourceLoader {
-    public static async groupByLocale(resourceExplorer: ResourceExplorer): Promise<Map<string, IResource[]>> {
+    public static groupByLocale(resourceExplorer: ResourceExplorer): Map<string, IResource[]> {
```
Comment (chrimc62) [inline libraries/botbuilder-dialogs-adaptive/src/languageResourceLoader.ts:17]: Documentation.

File: libraries/botbuilder-dialogs-adaptive/src/languageResourceLoader.ts [hunk 15]
```diff
@@ -14,9 +14,9 @@ import { IResource, ResourceExplorer } from 'botbuilder-dialogs-declarative';
...
         const resourceMapping: Map<string, IResource[]> = new Map<string, IResource[]>();
```
Comment (chrimc62) [inline libraries/botbuilder-dialogs-adaptive/src/languageResourceLoader.ts:18]: Documentation

**Comment by chrimc62** [comment]
>      * @param turnContext turnContext.

Turn context.

---
Refers to: libraries/botbuilder-dialogs-adaptive/src/languageGenerator.ts:17 in 37fd73a. [](commit_id = 37fd73af7be815881c36c72fd4d21adab0dc1bc8, deletion_comment = False)

**Comment by chrimc62** [comment]
>      * @param template template.

Template

---
Refers to: libraries/botbuilder-dialogs-adaptive/src/languageGenerator.ts:18 in 37fd73a. [](commit_id = 37fd73af7be815881c36c72fd4d21adab0dc1bc8, deletion_comment = False)

File: libraries/botbuilder-dialogs-adaptive/src/languageGenerator.ts [hunk 16]
```diff
@@ -19,5 +19,5 @@ export interface LanguageGenerator {
      * @param data data to bind to.
```
Comment (chrimc62) [inline libraries/botbuilder-dialogs-adaptive/src/languageGenerator.ts:19]: >data [](start = 19, length = 4)

Data

File: libraries/botbuilder-dialogs-adaptive/src/languageGenerator.ts [hunk 17]
```diff
@@ -19,5 +19,5 @@ export interface LanguageGenerator {
...
      * @returns text.
```
Comment (chrimc62) [inline libraries/botbuilder-dialogs-adaptive/src/languageGenerator.ts:20]: >text [](start = 16, length = 4)

What text?  How about "result of expanding template using data"

File: libraries/botbuilder-dialogs-adaptive/src/resourceExtensions.ts [hunk 18]
```diff
@@ -0,0 +1,22 @@
...
+/**
+ * Copyright (c) Microsoft Corporation. All rights reserved.
+ * Licensed under the MIT License.
+ */
+
+import { DialogManager } from 'botbuilder-dialogs';
+import { ResourceExplorer } from 'botbuilder-dialogs-declarative';
+
+export const resourceExplorerKey = Symbol('ResourceExplorer');
+
```
Comment (chrimc62) [inline libraries/botbuilder-dialogs-adaptive/src/resourceExtensions.ts:13]: Documentation

File: libraries/botbuilder-dialogs-adaptive/src/resourceExtensions.ts [hunk 19]
```diff
@@ -0,0 +1,22 @@
...
+export class ResourceExtensions {
+    /**
```
Comment (chrimc62) [inline libraries/botbuilder-dialogs-adaptive/src/resourceExtensions.ts:15]: Documentation

File: libraries/botbuilder-dialogs-adaptive/src/resourceExtensions.ts [hunk 20]
```diff
@@ -0,0 +1,22 @@
...
+     * Register ResourceExplorer into DialogManager.
+     */
+    public static useResourceExplorer(dialogManager: DialogManager, resourceExplorer: ResourceExplorer): DialogManager {
```
Comment (chrimc62) [inline libraries/botbuilder-dialogs-adaptive/src/resourceExtensions.ts:18]: >ialogManager: DialogManager, resourceExplorer: ResourceExplorer): DialogManager [](start = 39, length = 79)

Documentation of parameters and return value.

**Comment by chrimc62** [comment]
>      * @param turnContext TurnContext.

Turn context.

---
Refers to: libraries/botbuilder-dialogs-adaptive/src/template.ts:18 in 37fd73a. [](commit_id = 37fd73af7be815881c36c72fd4d21adab0dc1bc8, deletion_comment = False)

File: libraries/botbuilder-dialogs-adaptive/src/template.ts [hunk 21]
```diff
@@ -19,5 +19,5 @@ export interface TemplateInterface<T> {
      * @param data data to bind to.
```
Comment (chrimc62) [inline libraries/botbuilder-dialogs-adaptive/src/template.ts:19]: >data [](start = 19, length = 4)

Data

File: libraries/botbuilder-dialogs-adaptive/src/template.ts [hunk 22]
```diff
@@ -19,5 +19,5 @@ export interface TemplateInterface<T> {
...
      * @returns instance.
```
Comment (chrimc62) [inline libraries/botbuilder-dialogs-adaptive/src/template.ts:20]: >instance [](start = 16, length = 8)

instance of what?

**Comment by chrimc62** [comment]
>     private _resourceExporer: ResourceExplorer;

Documentation

---
Refers to: libraries/botbuilder-dialogs-adaptive/src/generators/languageGeneratorManager.ts:21 in 37fd73a. [](commit_id = 37fd73af7be815881c36c72fd4d21adab0dc1bc8, deletion_comment = False)

File: libraries/botbuilder-dialogs-adaptive/src/generators/languageGeneratorManager.ts [hunk 23]
```diff
@@ -27,18 +27,16 @@ export class LanguageGeneratorManager {
 
     public constructor(resourceManager: ResourceExplorer) {
         this._resourceExporer = resourceManager;
```
Comment (chrimc62) [inline libraries/botbuilder-dialogs-adaptive/src/generators/languageGeneratorManager.ts:29]: documentation

File: libraries/botbuilder-dialogs-adaptive/src/generators/languageGeneratorManager.ts [hunk 24]
```diff
@@ -27,18 +27,16 @@ export class LanguageGeneratorManager {
...
+        const resources = this._resourceExporer.getResources('lg');
         for (const resource of resources) {
-            const generator = await this.getTemplateEngineLanguageGenerator(resource);
-            this.languageGenerator.set(resource.id(), generator);
+            this.languageGenerators.set(resource.id(), this.getTemplateEngineLanguageGenerator(resource));
         }
     }
     
-    public languageGenerator: Map<string, LanguageGenerator> = new Map<string, LanguageGenerator>();
+    public languageGenerators: Map<string, LanguageGenerator> = new Map<string, LanguageGenerator>();
```
Comment (chrimc62) [inline libraries/botbuilder-dialogs-adaptive/src/generators/languageGeneratorManager.ts:40]: Documentation

File: libraries/botbuilder-dialogs-adaptive/src/generators/languageGeneratorManager.ts [hunk 25]
```diff
@@ -27,18 +27,16 @@ export class LanguageGeneratorManager {
...
 
     public static resourceExplorerResolver(locale: string, resourceMapping: Map<string, IResource[]>): ImportResolverDelegate {
         return  (source: string, id: string): {content: string; id: string} => {
```
Comment (chrimc62) [inline libraries/botbuilder-dialogs-adaptive/src/generators/languageGeneratorManager.ts:42]: Documentation

**Comment by chrimc62** [comment]
> 

Documentation

---
Refers to: libraries/botbuilder-dialogs-adaptive/src/generators/multiLanguageGenerator.ts:19 in 37fd73a. [](commit_id = 37fd73af7be815881c36c72fd4d21adab0dc1bc8, deletion_comment = False)

File: libraries/botbuilder-dialogs-adaptive/src/generators/multiLanguageGenerator.ts [hunk 26]
```diff
@@ -20,7 +21,7 @@ export class MultiLanguageGenerator extends MultiLanguageGeneratorBase{
         super();
     }
 
-    public tryGetGenerator(context: TurnContext, locale: string):  {exist: boolean; result: LanguageGenerator} {
+    public tryGetGenerator(dialogContext: DialogContext, locale: string):  {exist: boolean; result: LanguageGenerator} {
         if (this.languageGenerators.has(locale)) {
```
Comment (chrimc62) [inline libraries/botbuilder-dialogs-adaptive/src/generators/multiLanguageGenerator.ts:25]: Documentation

File: libraries/botbuilder-dialogs-adaptive/src/generators/multiLanguageGeneratorBase.ts [hunk 27]
```diff
@@ -6,31 +6,32 @@
...
  * This class automatically updates the cache when resource change events occure.
  */
 export abstract class MultiLanguageGeneratorBase implements LanguageGenerator{
     public languagePolicy: any;
 
-    public abstract tryGetGenerator(context: TurnContext, locale: string): {exist: boolean; result: LanguageGenerator};
+    public abstract tryGetGenerator(dialogContext: DialogContext, locale: string): { exist: boolean; result: LanguageGenerator };
 
     public constructor(languagePolicy: any = undefined) {
         this.languagePolicy = languagePolicy;
```
Comment (chrimc62) [inline libraries/botbuilder-dialogs-adaptive/src/generators/multiLanguageGeneratorBase.ts:23]: Documentation.

File: libraries/botbuilder-dialogs-adaptive/src/generators/multiLanguageGeneratorBase.ts [hunk 28]
```diff
@@ -6,31 +6,32 @@
...
 import { LanguageGenerator } from '../languageGenerator';
-import { TurnContext } from 'botbuilder-core';
-import {LanguagePolicy} from '../languagePolicy';
+import { LanguagePolicy } from '../languagePolicy';
+import { languagePolicyKey } from '../languageGeneratorExtensions';
 /**
  * Class which manages cache of all LG resources from a ResourceExplorer. 
  * This class automatically updates the cache when resource change events occure.
  */
 export abstract class MultiLanguageGeneratorBase implements LanguageGenerator{
```
Comment (chrimc62) [inline libraries/botbuilder-dialogs-adaptive/src/generators/multiLanguageGeneratorBase.ts:17]: >anguageGenerator{ [](start = 61, length = 17)

Spacing?

File: libraries/botbuilder-dialogs-adaptive/src/generators/multiLanguageGeneratorBase.ts [hunk 29]
```diff
@@ -6,31 +6,32 @@
...
+    public abstract tryGetGenerator(dialogContext: DialogContext, locale: string): { exist: boolean; result: LanguageGenerator };
 
     public constructor(languagePolicy: any = undefined) {
         this.languagePolicy = languagePolicy;
     };
     
-    public async generate(turnContext: TurnContext, template: string, data: object): Promise<string> {
-        const targetLocale = turnContext.activity.locale? turnContext.activity.locale.toLocaleLowerCase() : '';
+    public async generate(dialogContext: DialogContext, template: string, data: object): Promise<string> {
+        const targetLocale = dialogContext.context.activity.locale? dialogContext.context.activity.locale.toLocaleLowerCase() : '';
```
Comment (chrimc62) [inline libraries/botbuilder-dialogs-adaptive/src/generators/multiLanguageGeneratorBase.ts:27]: Documentation.

**Comment by chrimc62** [comment]
> 

Documentaiton

---
Refers to: libraries/botbuilder-dialogs-adaptive/src/generators/resourceMultiLanguageGenerator.ts:20 in 37fd73a. [](commit_id = 37fd73af7be815881c36c72fd4d21adab0dc1bc8, deletion_comment = False)

**Comment by chrimc62** [comment]
>         super(languagePolicy);

Documentation

---
Refers to: libraries/botbuilder-dialogs-adaptive/src/generators/resourceMultiLanguageGenerator.ts:22 in 37fd73a. [](commit_id = 37fd73af7be815881c36c72fd4d21adab0dc1bc8, deletion_comment = False)

File: libraries/botbuilder-dialogs-adaptive/src/generators/resourceMultiLanguageGenerator.ts [hunk 30]
```diff
@@ -22,11 +23,11 @@ export class ResourceMultiLanguageGenerator extends MultiLanguageGeneratorBase {
         this.resourceId = resourceId;
     }
 
-    public tryGetGenerator(context: TurnContext, locale: string): {exist: boolean; result: LanguageGenerator} {
-        const lgm: LanguageGeneratorManager = context.turnState.get('LanguageGeneratorManager');
+    public tryGetGenerator(dialogContext: DialogContext, locale: string): {exist: boolean; result: LanguageGenerator} {
+        const lgm: LanguageGeneratorManager = dialogContext.services.get(languageGeneratorManagerKey);
```
Comment (chrimc62) [inline libraries/botbuilder-dialogs-adaptive/src/generators/resourceMultiLanguageGenerator.ts:27]: Documentation

**Comment by chrimc62** [comment]
>     private readonly DEFAULTLABEL: string  = 'Unknown';

Documentation for publics

---
Refers to: libraries/botbuilder-dialogs-adaptive/src/generators/templateEngineLanguageGenerator.ts:21 in 37fd73a. [](commit_id = 37fd73af7be815881c36c72fd4d21adab0dc1bc8, deletion_comment = False)

File: libraries/botbuilder-dialogs-adaptive/src/templates/activityTemplate.ts [hunk 31]
```diff
@@ -1,6 +1,16 @@
...
+ */
+
+import { DialogContext } from 'botbuilder-dialogs';
+import { Activity, ActivityFactory, MessageFactory } from 'botbuilder-core';
 import { TemplateInterface } from '../template';
 import { LanguageGenerator } from '../languageGenerator';
+import { languageGeneratorKey } from '../languageGeneratorExtensions';
 
 export class ActivityTemplate implements TemplateInterface<Partial<Activity>> {
     public template: string;
```
Comment (chrimc62) [inline libraries/botbuilder-dialogs-adaptive/src/templates/activityTemplate.ts:16]: Document class and publics.

File: libraries/botbuilder-dialogs-adaptive/src/templates/staticActivityTemplate.ts [hunk 32]
```diff
@@ -1,15 +1,24 @@
...
+ * Copyright (c) Microsoft Corporation. All rights reserved.
+ * Licensed under the MIT License.
+ */
+
+import { DialogContext } from 'botbuilder-dialogs';
+import { Activity } from 'botbuilder-core';
 import { TemplateInterface } from '../template';
-import { Activity, TurnContext } from 'botbuilder-core';
 
 export class StaticActivityTemplate implements TemplateInterface<Partial<Activity>> {
```
Comment (chrimc62) [inline libraries/botbuilder-dialogs-adaptive/src/templates/staticActivityTemplate.ts:14]: Document class and publics

File: libraries/botbuilder-dialogs-adaptive/src/templates/textTemplate.ts [hunk 33]
```diff
@@ -1,6 +1,15 @@
...
+ * Licensed under the MIT License.
+ */
+
+import { DialogContext } from 'botbuilder-dialogs';
 import { TemplateInterface } from '../template';
-import { TurnContext } from 'botbuilder-core';
 import { LanguageGenerator } from '../languageGenerator';
+import { languageGeneratorKey } from '../languageGeneratorExtensions';
 
 export class TextTemplate implements TemplateInterface<string> {
```
Comment (chrimc62) [inline libraries/botbuilder-dialogs-adaptive/src/templates/textTemplate.ts:15]: Document class and publics

File: libraries/botbuilder-dialogs-adaptive/src/generators/multiLanguageGeneratorBase.ts (hunk 28 above)
Comment (chon219) [reply libraries/botbuilder-dialogs-adaptive/src/generators/multiLanguageGeneratorBase.ts]: yes we need to have spacing around imported items.

File: libraries/botbuilder-dialogs-adaptive/src/templates/staticActivityTemplate.ts [hunk 34]
```diff
@@ -1,17 +1,41 @@
+/**
+ * @module botbuilder-dialogs-adaptive
+ */
+/**
+ * Copyright (c) Microsoft Corporation. All rights reserved.
+ * Licensed under the MIT License.
+ */
+
+import { DialogContext } from 'botbuilder-dialogs';
+import { Activity } from 'botbuilder-core';
```
Comment (stevengum) [inline libraries/botbuilder-dialogs-adaptive/src/templates/staticActivityTemplate.ts:10]: alphabetically sort module imports

File: libraries/botbuilder-dialogs-adaptive/src/templates/activityTemplate.ts [hunk 35]
```diff
@@ -1,29 +1,55 @@
...
+/**
+ * @module botbuilder-dialogs-adaptive
+ */
+/**
+ * Copyright (c) Microsoft Corporation. All rights reserved.
+ * Licensed under the MIT License.
+ */
+
+import { DialogContext } from 'botbuilder-dialogs';
+import { Activity, ActivityFactory, MessageFactory } from 'botbuilder-core';
```
Comment (stevengum) [inline libraries/botbuilder-dialogs-adaptive/src/templates/activityTemplate.ts:10]: alphabetically sort module imports

File: libraries/botbuilder-dialogs-adaptive/src/languageGeneratorExtensions.ts [hunk 36]
```diff
@@ -0,0 +1,77 @@
...
+        if (typeof(lg) === 'string') {
+            const resource = resourceExplorer.getResource(lg);
+            if (resource) {
+                languageGenerator = new ResourceMultiLanguageGenerator(lg);
+            } else {
+                languageGenerator = new TemplateEngineLanguageGenerator();
+            }
+        } else {
+            languageGenerator = lg;
+        }
```
Comment (stevengum) [inline libraries/botbuilder-dialogs-adaptive/src/languageGeneratorExtensions.ts:57]:
```suggestion
        let languageGenerator = lg || 'main.lg';

        if (typeof(lg) === 'string') {
            const resource = resourceExplorer.getResource(lg);
            if (resource) {
                languageGenerator = new ResourceMultiLanguageGenerator(lg);
            } else {
                languageGenerator = new TemplateEngineLanguageGenerator();
            }
        }
```

File: libraries/adaptive-expressions/src/expressionProperties/stringExpression.ts [hunk 37]
```diff
@@ -27,34 +27,31 @@ export class StringExpression extends ExpressionProperty<string> {
...
-    }
-    
-    public setValue(value: string | Expression): void {
-        this.value = undefined;
-        this.expression = undefined;
-
-        if (typeof value == 'string' && !value.startsWith('=')) {
-            // Trim off the escape char for equals (\=foo) should simply be the string (=foo).
-            if (value.startsWith('\\=')) {
+        if (typeof value == 'string') {
```
[the remark this answers is not in the document]
Comment (chon219) [reply libraries/adaptive-expressions/src/expressionProperties/stringExpression.ts:43]: > want

Got it, btw, do we need to add type check for all kinds of expression properties?

File: libraries/botbuilder-dialogs-adaptive/src/languageGeneratorExtensions.ts (hunk 36 above)
Comment (chon219) [reply libraries/botbuilder-dialogs-adaptive/src/languageGeneratorExtensions.ts]: If lg is undefined, languageGenerator cannot be initialized correctly.
How about use `if (typeof(languageGenerator) === 'string')` instead?

File: libraries/adaptive-expressions/src/expressionProperties/stringExpression.ts (hunk 37 above)
[the remark this answers is not in the document]
Comment (stevengum) [reply libraries/adaptive-expressions/src/expressionProperties/stringExpression.ts:43]: I think we should, but I've created a new issue to track it for another milestone: https://github.com/microsoft/botbuilder-js/issues/2568

FYI @luhan2017

File: libraries/botbuilder-dialogs-adaptive/src/languageGeneratorExtensions.ts (hunk 36 above)
Comment (stevengum) [reply libraries/botbuilder-dialogs-adaptive/src/languageGeneratorExtensions.ts]: good catch, I meant to replace those instances of `lg` but forgot to.

File: libraries/adaptive-expressions/src/expressionProperties/stringExpression.ts (hunk 37 above)
[the remark this answers is not in the document]
Comment (stevengum) [reply libraries/adaptive-expressions/src/expressionProperties/stringExpression.ts:43]: I've backed out the change so that we can keep the same behavior in the other ExpressionProperties... Thanks for applying the feedback! Let's pick up the discussion in #2568.
