### PR TITLE
fix: single orchestrator bug and #3841

### LINKED ISSUE #3841: When entity model is available, OrchestratorRecognizer failed to load it

### PR DESCRIPTION
**Pull request by hcyang**
Fixes #3841 

## Description
Current OrchestratorRecognizer implement can only uses one Ochestrator object.
This fix is a parallel of the the fix (https://github.com/microsoft/botbuilder-dotnet/pull/5749) for the dotnet issue https://github.com/microsoft/botbuilder-dotnet/issues/5750

## Specific Changes

  - 
  -
  -

### CODE REVIEW

File: libraries/botbuilder-ai-orchestrator/src/orchestratorRecognizer.ts [hunk 1]
```diff
@@ -187,42 +189,33 @@ export class OrchestratorRecognizer extends AdaptiveRecognizer implements Orches
...
-            recognizerResult.entities = externalResults.entities;
-        }
-
         // Score with orchestrator
-        const results = await this._resolver.score(text);
+        const results = await this._resolver?.score(text);
 
-        // Add full recognition result as a 'result' property
-        recognizerResult[this.resultProperty] = results;
+        if (results && results.length) {
```
Comment (tsuwandy) [inline libraries/botbuilder-ai-orchestrator/src/orchestratorRecognizer.ts:200]: You want to add to recognizerResult[this.resultProperty] regardless if it's empty, this is for telemetry

File: libraries/botbuilder-ai-orchestrator/src/orchestratorRecognizer.ts [hunk 2]
```diff
@@ -257,7 +250,18 @@ export class OrchestratorRecognizer extends AdaptiveRecognizer implements Orches
             recognizerResult.intents.None = { score: 1.0 };
         }
 
-        await this.tryScoreEntities(text, recognizerResult);
+        if (this.externalEntityRecognizer) {
```
Comment (tsuwandy) [inline libraries/botbuilder-ai-orchestrator/src/orchestratorRecognizer.ts:253]: Why should this be outside tryScoreEntities?  externalEntities are entities.

File: libraries/botbuilder-ai-orchestrator/src/orchestratorRecognizer.ts [hunk 3]
```diff
@@ -337,100 +345,137 @@ export class OrchestratorRecognizer extends AdaptiveRecognizer implements Orches
...
-                const entityText = text.substr(span.offset, span.length);
-                values.push({
-                    type: entityType,
-                    score: result.score,
-                    text: entityText,
-                    start: span.offset,
-                    end: span.offset + span.length,
-                });
+        // As this method is TryScoreEntities, so it's best effort only, there should
+        // not be any exception thrown out of this method.
```
Comment (tsuwandy) [inline libraries/botbuilder-ai-orchestrator/src/orchestratorRecognizer.ts:431]: Actually it was named TryScoreEntities because there might not be entities extracted. :-)

File: libraries/botbuilder-ai-orchestrator/src/orchestratorRecognizer.ts (hunk 1 above)
Comment (hcyang) [reply libraries/botbuilder-ai-orchestrator/src/orchestratorRecognizer.ts:200]: It's in there, it's just been moved within the if (results...) statement.

File: libraries/botbuilder-ai-orchestrator/src/orchestratorRecognizer.ts [hunk 4]
```diff
@@ -337,100 +345,137 @@ export class OrchestratorRecognizer extends AdaptiveRecognizer implements Orches
...
+                        endIndex: span.offset + span.length,
+                        score: result.score,
+                        text: entityText,
+                        type: entityType,
+                    });
                 });
-            });
+            }
+            // eslint-disable-next-line @typescript-eslint/no-unused-vars
+        } catch (error) {
```
Comment (tsuwandy) [inline libraries/botbuilder-ai-orchestrator/src/orchestratorRecognizer.ts:477]: Let's remove the try catch so we don't mask some issues that should be surfaced.   It was named that way because there might not be entities extracted.   If you added try catch in c#, then leave it, however, take out the error since it's not used.  try {} catch {}

File: libraries/botbuilder-ai-orchestrator/src/orchestratorRecognizer.ts (hunk 2 above)
Comment (hcyang) [reply libraries/botbuilder-ai-orchestrator/src/orchestratorRecognizer.ts:253]: It's never inside the tryScoreEntities() function (as does the C# version), I simply moved its location from before tryScoreEntities() to after to be in sync with the original C# implementation.
This PR only tries to make this JS version in sync with the C# one and fix some bugs. If you wish, we can expand the scope on refactoring the overall code structure, but I think it would be better for another PR.

File: libraries/botbuilder-ai-orchestrator/src/orchestratorRecognizer.ts (hunk 3 above)
Comment (hcyang) [reply libraries/botbuilder-ai-orchestrator/src/orchestratorRecognizer.ts:431]: Agreed, I still keep the original code (see below) of throwing an exception, but wrap it in an try-catch -- for the best effort and no entity scenario. 

            const results = await this._resolver.score(text, LabelType.Entity);
            if (!results) {
                throw new Error(`Failed scoring entities for: ${text}`);
            }

File: libraries/botbuilder-ai-orchestrator/src/orchestratorRecognizer.ts (hunk 4 above)
Comment (hcyang) [reply libraries/botbuilder-ai-orchestrator/src/orchestratorRecognizer.ts:477]: Will remove (error)

File: libraries/botbuilder-ai-orchestrator/src/orchestratorRecognizer.ts [hunk 5]
```diff
@@ -309,24 +317,24 @@ export class OrchestratorRecognizer extends AdaptiveRecognizer implements Orches
...
+            NextIntentScore: intent.length > 1 ? topTwo[1].score.toString() : '',
+            Intents: intent.length > 0 ? JSON.stringify(recognizerResult.intents) : '',
+            Entities: recognizerResult.entities ? JSON.stringify(recognizerResult.entities) : '',
             AdditionalProperties: JSON.stringify(customRecognizerProps),
         };
 
         let logPersonalInformation =
             this.logPersonalInformation instanceof BoolExpression
-                ? this.logPersonalInformation.getValue(dialogContext.state)
+                ? this.logPersonalInformation.getValue((dialogContext as DialogContext).state)
```
Comment (joshgummersall) [inline libraries/botbuilder-ai-orchestrator/src/orchestratorRecognizer.ts:331]: ` as DialogContext` should be unnecessary.

File: libraries/botbuilder-ai-orchestrator/src/orchestratorRecognizer.ts [hunk 6]
```diff
@@ -309,24 +317,24 @@ export class OrchestratorRecognizer extends AdaptiveRecognizer implements Orches
...
                 : this.logPersonalInformation;
         if (logPersonalInformation == undefined) logPersonalInformation = false;
 
         if (logPersonalInformation) {
             properties['Text'] = recognizerResult.text;
-            properties['AlteredText'] = recognizerResult.alteredText;
+            properties['AlteredText'] = recognizerResult.alteredText as string;
```
Comment (joshgummersall) [inline libraries/botbuilder-ai-orchestrator/src/orchestratorRecognizer.ts:337]: Why is this `as string` necessary?

File: libraries/botbuilder-ai-orchestrator/src/orchestratorRecognizer.ts [hunk 7]
```diff
@@ -337,100 +345,136 @@ export class OrchestratorRecognizer extends AdaptiveRecognizer implements Orches
...
-            const fullModelFolder = resolve(this._modelFolder);
-            if (!existsSync(fullModelFolder)) {
-                throw new Error(`Model folder does not exist at ${fullModelFolder}.`);
-            }
+        // Create orchestrator core
+        const fullModelFolder: string = resolve(modelFolder);
+
+        this._orchestrator = OrchestratorRecognizer.orchestratorMap.has(fullModelFolder)
+            ? OrchestratorRecognizer.orchestratorMap.get(fullModelFolder)
+            : ((): OrchestratorDictionaryEntry => {
```
Comment (joshgummersall) [inline libraries/botbuilder-ai-orchestrator/src/orchestratorRecognizer.ts:371]: Why an IIFE?
```typescript
this._orchestrator = OrchestratorRecognizer.orchestratorMap.get();
if (!this._orchestrator) {
  /// contents of IIFE
}
```

File: libraries/botbuilder-ai-orchestrator/src/orchestratorRecognizer.ts [hunk 8]
```diff
@@ -337,100 +345,136 @@ export class OrchestratorRecognizer extends AdaptiveRecognizer implements Orches
...
+        // NOTE: SHOULD consider removing this flag in the next major SDK release (V5).
         if (!this.scoreEntities) {
             return;
         }
 
-        const results = await this._resolver.score(text, LabelType.Entity);
-        if (!results) {
-            throw new Error(`Failed scoring entities for: ${text}`);
+        // The following check is necessary to ensure that the _resolver object
+        // is capable of entity exttraction. However, this check does not apply to
```
Comment (joshgummersall) [inline libraries/botbuilder-ai-orchestrator/src/orchestratorRecognizer.ts:422]: *extraction

File: libraries/botbuilder-ai-orchestrator/src/orchestratorRecognizer.ts [hunk 9]
```diff
@@ -130,27 +136,27 @@ export class OrchestratorRecognizer extends AdaptiveRecognizer implements Orches
     }
 
     private readonly unknownIntentFilterScore = 0.4;
-    private static orchestrator: Orchestrator;
-    private _resolver: LabelResolver;
-    private _modelFolder: string;
-    private _snapshotFile: string;
+    private static orchestratorMap: Map<string, OrchestratorDictionaryEntry> = new Map<
```
[the remark this answers is not in the document]
Comment (hcyang) [reply libraries/botbuilder-ai-orchestrator/src/orchestratorRecognizer.ts:139]: Yeah, want to be explicit like working with a strong-typed language.

File: libraries/botbuilder-ai-orchestrator/src/orchestratorRecognizer.ts [hunk 10]
```diff
@@ -92,12 +97,13 @@ export class OrchestratorRecognizer extends AdaptiveRecognizer implements Orches
     /**
      * The external entity recognizer.
      */
-    externalEntityRecognizer: Recognizer;
+    externalEntityRecognizer?: Recognizer = undefined;
```
[the remark this answers is not in the document]
Comment (hcyang) [reply libraries/botbuilder-ai-orchestrator/src/orchestratorRecognizer.ts:100]: Yeah, it's kind of explicit documentation. Some lint asks for it.

File: libraries/botbuilder-ai-orchestrator/src/orchestratorRecognizer.ts [hunk 11]
```diff
@@ -130,27 +136,27 @@ export class OrchestratorRecognizer extends AdaptiveRecognizer implements Orches
...
-    private static orchestrator: Orchestrator;
-    private _resolver: LabelResolver;
-    private _modelFolder: string;
-    private _snapshotFile: string;
+    private static orchestratorMap: Map<string, OrchestratorDictionaryEntry> = new Map<
+        string,
+        OrchestratorDictionaryEntry
+    >();
+    private _orchestrator?: OrchestratorDictionaryEntry = undefined;
+    private _resolver?: LabelResolver = undefined;
```
[the remark this answers is not in the document]
Comment (hcyang) [reply libraries/botbuilder-ai-orchestrator/src/orchestratorRecognizer.ts:144]: Same above.

File: libraries/botbuilder-ai-orchestrator/src/orchestratorRecognizer.ts [hunk 12]
```diff
@@ -187,42 +189,33 @@ export class OrchestratorRecognizer extends AdaptiveRecognizer implements Orches
             entities: {},
         };
 
-        if (text === '') {
+        if (!text || text === '') {
```
[the remark this answers is not in the document]
Comment (hcyang) [reply libraries/botbuilder-ai-orchestrator/src/orchestratorRecognizer.ts:192]: will remove the original === '' part.

File: libraries/botbuilder-ai-orchestrator/src/orchestratorRecognizer.ts [hunk 13]
```diff
@@ -281,7 +289,7 @@ export class OrchestratorRecognizer extends AdaptiveRecognizer implements Orches
         }
         const intents = Object.entries(result.intents)
             .map((intent) => {
-                return { name: intent[0], score: +intent[1].score };
+                return { name: intent[0], score: +(intent[1].score as number) };
```
[the remark this answers is not in the document]
Comment (hcyang) [reply libraries/botbuilder-ai-orchestrator/src/orchestratorRecognizer.ts:292]: Some lint asks for it, even though not enforced here.

File: libraries/botbuilder-ai-orchestrator/src/orchestratorRecognizer.ts (hunk 5 above)
Comment (hcyang) [reply libraries/botbuilder-ai-orchestrator/src/orchestratorRecognizer.ts:331]: Some other lint and environment asked for it, though not here. Just try to appease to both lint.

File: libraries/botbuilder-ai-orchestrator/src/orchestratorRecognizer.ts (hunk 6 above)
Comment (hcyang) [reply libraries/botbuilder-ai-orchestrator/src/orchestratorRecognizer.ts:337]: Same as above.

File: libraries/botbuilder-ai-orchestrator/src/orchestratorRecognizer.ts (hunk 7 above)
Comment (hcyang) [reply libraries/botbuilder-ai-orchestrator/src/orchestratorRecognizer.ts:371]: No idea, inherited from the original code. Not in scope for this bug-fixing PR.

File: libraries/botbuilder-ai-orchestrator/src/orchestratorRecognizer.ts (hunk 8 above)
Comment (hcyang) [reply libraries/botbuilder-ai-orchestrator/src/orchestratorRecognizer.ts:422]: Thanks, will fix the typo.

File: libraries/botbuilder-ai-orchestrator/src/orchestratorRecognizer.ts (hunk 1 above)
[the remark this answers is not in the document]
Comment (hcyang) [reply libraries/botbuilder-ai-orchestrator/src/orchestratorRecognizer.ts:200]: Will do.

File: libraries/botbuilder-ai-orchestrator/src/orchestratorRecognizer.ts [hunk 14]
```diff
@@ -268,7 +272,11 @@ export class OrchestratorRecognizer extends AdaptiveRecognizer implements Orches
         this.trackRecognizerResult(
             dc,
             'OrchestratorRecognizerResult',
-            this.fillRecognizerResultTelemetryProperties(recognizerResult, telemetryProperties, dc),
+            this.fillRecognizerResultTelemetryProperties(
+                recognizerResult,
+                telemetryProperties as Record<string, string>,
```
[the remark this answers is not in the document]
Comment (hcyang) [reply libraries/botbuilder-ai-orchestrator/src/orchestratorRecognizer.ts:277]: Converting from "telemetryProperties?: Record<string, string>" to fillRecognizerResultTelemetryProperties() argument, whose type is simply "Record<string, string>"

**Review by tsuwandy — APPROVED** [review]

File: libraries/botbuilder-ai-orchestrator/src/orchestratorRecognizer.ts (hunk 9 above)
[the remark this answers is not in the document]
Comment (joshgummersall) [reply libraries/botbuilder-ai-orchestrator/src/orchestratorRecognizer.ts:139]: That's not the convention we use in this repo, the explicit typing on the left hand side is redundant. Type inference exists in [Java](https://docs.oracle.com/javase/tutorial/java/generics/genTypeInference.html) and [.NET](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/implicitly-typed-local-variables).

**Review by joshgummersall — APPROVED** [review]

File: libraries/botbuilder-ai-orchestrator/src/orchestratorRecognizer.ts (hunk 9 above)
[the remark this answers is not in the document]
Comment (hcyang) [reply libraries/botbuilder-ai-orchestrator/src/orchestratorRecognizer.ts:139]: Will remove the declaration.
