### PR TITLE
fix: more permissive type assertions

### LINKED ISSUE #3684: Transcript logger middleware throwing error with botbuilder-azure-blobs library
## Versions
What package version of the SDK are you using.
4.13.2
What nodejs version are you using
10.24.1
What os are you using
Windows 10
## Describe the bug
When switching over to the botbuilder-azure-blobs library the transcript logger middleware is throwing the below error
Error: activity.localTimezone must be defined
at Object.assertCondition (C:\Users\user\Desktop\Cori\CORI_Virtual_Assistant\node_modules\botbuilder-stdlib\lib\assertExt.js:15:15)
at condition (C:\Users\user\Desktop\Cori\CORI_Virtual_Assistant\node_modules\botbuilder-stdlib\lib\types.js:26:17)
at C:\Users\user\Desktop\Cori\CORI_Virtual_Assistant\node_modules\botbuilder-stdlib\lib\types.js:40:13
at Object.string (C:\Users\user\Desktop\Cori\CORI_Virtual_Assistant\node_modules\botbuilder-stdlib\lib\types.js:347:5)
at Object.exports.assertActivity (C:\Users\user\Desktop\Cori\CORI_Virtual_Assistant\node_modules\botframework-schema\lib\index.js:134:32)
at BlobsTranscriptStore. (C:\Users\user\Desktop\Cori\CORI_Virtual_Assistant\node_modules\botbuilder-azure-blobs\lib\blobsTranscriptStore.js:204:31)
at Generator.next ()
at C:\Users\user\Desktop\Cori\CORI_Virtual_Assistant\node_modules\botbuilder-azure-blobs\lib\blobsTranscriptStore.js:10:71
at new Promise ()
at __awaiter (C:\Users\user\Desktop\Cori\CORI_Virtual_Assistant\node_modules\botbuilder-azure-blobs\lib\blobsTranscriptStore.js:6:12)

## To Reproduce
1. install botbuilder-azure-blobs library
2. change the transcript logger middleware to use BlobsTranscriptStore
3. Run the bot

## Expected behavior
Transcript logger middleware log the transcripts to blob

## Additional context
I am changing over to use the botbuilder-azure-blobs library and removing the botbuilder-azure library, the logger middleware runs as expected with the old library but when you switch it will throw the above error on every turn of the conversation

### PR DESCRIPTION
**Pull request by joshgummersall**
Fixes #3684

### CODE REVIEW

File: libraries/botbuilder-azure-blobs/src/blobsTranscriptStore.ts [hunk 1]
```diff
@@ -251,7 +248,7 @@ export class BlobsTranscriptStore implements TranscriptStore {
      * @returns {Promise<void>} A promise representing the async operation.
      */
     async logActivity(activity: Activity): Promise<void> {
-        assertActivity(activity, ['activity']);
+        t.Record({ activity: t.Dictionary(t.Unknown, t.String) }).check({ activity });
```
Comment (mdrichardson) [inline libraries/botbuilder-azure-blobs/src/blobsTranscriptStore.ts:251]: I'm guessing this is the line that directly addresses the issue. Since we know the structure of `Activity`, would it make sense to check the keys and not the values, to ensure we don't get an activity with an invalid key or something (if possible)?

Comment (joshgummersall) [reply libraries/botbuilder-azure-blobs/src/blobsTranscriptStore.ts:251]: Initially, I thought we ought to be quite restrictive in our type assertions. After a few instances of this kind of issue, along with encouragement from @stevengum, I think I'm in favor of more permissive type checks. In this particular scenario, we want to ensure that we have some kind of object that we can log. It doesn't absolutely have to be a perfectly formatted Activity.

I do think we are due for some runtime type checking overhauls which I think we can address when we start working on https://github.com/microsoft/botbuilder-js/issues/3670.

**Review by mdrichardson — APPROVED** [review]

File: libraries/botbuilder-azure-blobs/src/blobsStorage.ts [hunk 2]
```diff
@@ -36,8 +36,7 @@ export class BlobsStorage implements Storage {
      * @param {BlobsStorageOptions} options Other options for BlobsStorage
      */
     constructor(connectionString: string, containerName: string, options?: BlobsStorageOptions) {
-        assert.string(connectionString, ['connectionString']);
-        assert.string(containerName, ['containerName']);
+        t.Record({ connectionString: t.String, containerName: t.String }).check({ connectionString, containerName });
```
Comment (stevengum) [inline libraries/botbuilder-azure-blobs/src/blobsStorage.ts:39]: Publicly asking: is the error message thrown from this straight forward?

Comment (joshgummersall) [reply libraries/botbuilder-azure-blobs/src/blobsStorage.ts:39]: Yes - the Record wrapping is to include the key in the error message:
```
> t.String.check(10)
Uncaught ValidationError: Expected string, but was number
    at new ValidationError (/Users/jpg/src/github/microsoft/botbuilder/js/node_modules/runtypes/lib/errors.js:22:28)
    at Object.check (/Users/jpg/src/github/microsoft/botbuilder/js/node_modules/runtypes/lib/runtype.js:30:15) {
  key: undefined
}
> t.Record({foo: t.String}).check({foo: 10})
Uncaught ValidationError: Expected string, but was number in foo
    at new ValidationError (/Users/jpg/src/github/microsoft/botbuilder/js/node_modules/runtypes/lib/errors.js:22:28)
    at Object.check (/Users/jpg/src/github/microsoft/botbuilder/js/node_modules/runtypes/lib/runtype.js:30:15) {
  key: 'foo'
}
```

Comment (joshgummersall) [reply libraries/botbuilder-azure-blobs/src/blobsStorage.ts:39]: Unfortunately, using `.withBrand('foo')` doesn't include it anywhere in the error message.

File: libraries/botbuilder-azure-blobs/src/blobsTranscriptStore.ts [hunk 3]
```diff
@@ -32,14 +32,14 @@ function getConversationPrefix(channelId: string, conversationId: string): strin
...
 // Formats an activity as a blob key
 function getBlobKey(activity: Activity): string {
-    assert.date(activity.timestamp, ['activity', 'timestamp']);
+    const { timestamp } = t.Record({ timestamp: DateT }).check(activity);
 
     return sanitizeBlobKey(
-        [activity.channelId, activity.conversation.id, `${formatTicks(activity.timestamp)}-${activity.id}.json`].join(
-            '/'
-        )
+        [activity.channelId, activity.conversation.id, `${formatTicks(timestamp)}-${activity.id}.json`].join('/')
```
Comment (stevengum) [inline libraries/botbuilder-azure-blobs/src/blobsTranscriptStore.ts:42]: Not something for this PR, but in v5 the behavior around generating keys needs to be locked down and inputs need to be validated.

Are `null`, `undefined`, empty strings or whitespace-only strings valid for conversation IDs?

**Review by stevengum — APPROVED** [review]
LGTM

**Comment by joshgummersall** [comment]
In lieu of Github Actions (current status is degraded perf), I've manually run the same CI suite via Dev Ops.

**Comment by joshgummersall** [comment]
Merging as ADO CI passed.
