### PR TITLE
fix: toJSON overrides

### LINKED ISSUE #3697: Identify classes that need custom toJSON
There are types that we really don't want to fully stringify in serialized payloads. Examples we recently fixed include the Azure Storage types (JSON stringify cycles and concerns around stringifying connection strings).

### PR DESCRIPTION
**Pull request by joshgummersall**
Fixes #3697

### CODE REVIEW

**Comment by mdrichardson** [comment]
Worth adding do [tokenApiClient](https://github.com/microsoft/botbuilder-js/blob/6fab548c8ade620a7eb3d8905729ff6cd0649237/libraries/botframework-connector/src/tokenApi/tokenApiClient.ts) and [certificateAppCredentials](https://github.com/microsoft/botbuilder-js/blob/6fab548c8ade620a7eb3d8905729ff6cd0649237/libraries/botframework-connector/src/auth/certificateAppCredentials.ts) ?

**Comment by joshgummersall** [comment]
`CertificationAppCredentials` derives from `AppCredentials` which provides the override. I'll add it to `tokenApiClient` though!

**Comment by mdrichardson** [comment]
> `CertificationAppCredentials` derives from `AppCredentials` which provides the override. I'll add it to `tokenApiClient` though!

Ah right. That will auto-exclude the thumbprint and privateKey.

**Comment by joshgummersall** [comment]
@mdrichardson, I went ahead and added an override to `TokenApiClientContext` which holds a reference to the credentials.

File: libraries/botframework-connector/src/auth/credentialProvider.ts [hunk 1]
```diff
@@ -58,6 +58,11 @@ export class SimpleCredentialProvider implements ICredentialProvider {
     private readonly appId: string;
     private readonly appPassword: string;
 
+    // Protects against JSON.stringify leaking secrets
+    private toJSON(): unknown {
+        return { name: this.constructor.name, appId: this.appId };
```
Comment (mdrichardson) [inline libraries/botframework-connector/src/auth/credentialProvider.ts:63]: Did we want to avoid `this.constructor.name`? I know we did in other areas in the event of minification; not sure if that applies here.

Comment (joshgummersall) [reply libraries/botframework-connector/src/auth/credentialProvider.ts:63]: I think using it as a key in turn state is problematic because users may interchangeably use `this.constructor.name` and the actual string key. If there is some minification that happens, the string keys will no longer work. In this case, I'm not worried about `JSON.stringify` output.

**Review by mdrichardson — APPROVED** [review]

**Review by carlosscastro — APPROVED** [review]
