### PR TITLE
Cached lgm initialization in lg extension

### LINKED ISSUE #2988: Resource Explorer registered duplicated LG resource listener
## Versions
main branch

## Describe the bug
Each time we use `useLanguageGeneration`, a new instance of `LanguageGeneratorManager` will be initialized and a new callback function will be registered to the resource explorer to monitor LG resource changes, which will cause warnings mentioned in #2699 .

### PR DESCRIPTION
**Pull request by chon219**
Fixes #2988 

## Description

Cached instances of `LanguageGeneratorManager` in `LanguageGeneratorExtensions` to avoid registering duplicated callbacks in resource explorer.

## Specific Changes

  - Cached lgm instance in LanguageGeneratorExtensions.useLanguageGenerator().
  -
  -

### CODE REVIEW

File: libraries/botbuilder-dialogs-adaptive/src/languageGeneratorExtensions.ts [hunk 1]
```diff
@@ -36,6 +36,11 @@ export const languagePolicyKey = Symbol('LanguagePolicy');
  * Extension methods for language generator.
  */
 export class LanguageGeneratorExtensions {
+    private static readonly _languageGeneratorManagers: Map<ResourceExplorer, LanguageGeneratorManager> = new Map<
```
Comment (joshgummersall) [inline libraries/botbuilder-dialogs-adaptive/src/languageGeneratorExtensions.ts:39]: Generally, the type can be inferred by initialization. In this case you can omit just write `private static readonly _languageGeneratorManagers = new Map<ResourceExplorer, LanguageGeneratorManager>();`

File: libraries/botbuilder-dialogs-adaptive/src/languageGeneratorExtensions.ts [hunk 2]
```diff
@@ -56,7 +61,11 @@ export class LanguageGeneratorExtensions {
             }
         }
 
-        const languageGeneratorManager: LanguageGeneratorManager = new LanguageGeneratorManager(resourceExplorer);
+        let languageGeneratorManager: LanguageGeneratorManager = this._languageGeneratorManagers.get(resourceExplorer);
```
Comment (joshgummersall) [inline libraries/botbuilder-dialogs-adaptive/src/languageGeneratorExtensions.ts:64]: Here you can drop the `: LanguageGeneratorManager` piece as well, the type should be properly inferred.

**Review by joshgummersall — APPROVED** [review]
Two small fixes, otherwise it looks good!

File: libraries/botbuilder-dialogs-adaptive/src/languageGeneratorExtensions.ts (hunk 2 above)
Comment (chon219) [reply libraries/botbuilder-dialogs-adaptive/src/languageGeneratorExtensions.ts]: Got it, thx.

**Comment by chon219** [comment]
@joshgummersall Caching lgm in a map may cause GC issues, check out this issue: https://github.com/microsoft/botbuilder-dotnet/issues/4871
Shall we use `WeakMap` instead of `Map` to fix this?

**Comment by joshgummersall** [comment]
I think a Weakmap would work for this use case as long as all the targets for this library support it.
