### PR TITLE
fix: turnContext updateActivity signature

### LINKED ISSUE #2937: Make turnContext.updateActivity return response
See https://github.com/microsoft/botbuilder-js/pull/2912#discussion_r509736781 and https://github.com/microsoft/botbuilder-dotnet/blob/main/libraries/Microsoft.Bot.Builder/TurnContext.cs#L379 for details.

### PR DESCRIPTION
**Pull request by joshgummersall**
Includes some assorted cleanup and fixes as well.

Fixes #2937

### CODE REVIEW

File: libraries/botbuilder-core/src/turnContext.ts [hunk 1]
```diff
@@ -804,26 +808,17 @@ export class TurnContext {
...
-                if (i < list.length) {
-                    return Promise.resolve(list[i](context, arg, () => emitNext(i + 1)));
-                }
-
-                return Promise.resolve(next());
-            } catch (err) {
-                return Promise.reject(err);
-            }
-        }
+    private emit<A, T>(
```
Comment (joshgummersall) [inline libraries/botbuilder-core/src/turnContext.ts:813]: This is the bulk of the PR: we now have a much more type-safe way of running emit handlers as a chain.

File: libraries/botbuilder/src/skills/skillHandler.ts [hunk 2]
```diff
@@ -323,13 +325,11 @@ export class SkillHandler extends ChannelServiceHandler {
...
 
-            return context.updateActivity(newActivity);
+            resourceResponse = await context.updateActivity(newActivity);
         });
 
-        // Note: the original activity ID is passed back here to provide "behavioral" parity with the C# SDK. Due to
-        // some inconsistent method signatures, the proper response is not propagated back through `context.updateActivity`
-        // so we have to manually pass this value back.
-        return { id: activityId };
+        // Due to a backwards-compat function signature, resourceResponse may not be defined.
```
Comment (stevengum) [inline libraries/botbuilder/src/skills/skillHandler.ts:331]: This was the primary blocker and lack of utility from the actual return value that kept us from taking this change; we were concerned about breaking people who implemented their own subclass of BotAdapter.

Apparently we just didn't devote enough time to thinking of another approach 😅 🤦‍♂️

**Review by stevengum — APPROVED** [review]

File: libraries/botbuilder/src/skills/skillHandler.ts (hunk 2 above)
Comment (joshgummersall) [reply libraries/botbuilder/src/skills/skillHandler.ts:331]: Just triple checked by extending from BotAdapter in the consumer-test script and making the `updateActivity` signature return just `Promise<void>`. Compilation with strict mode worked no problem. Changing the signature to return `Promise<boolean>` yields a compilation error 👍
