### PR TITLE
port: add command/commandResult activity types

### LINKED ISSUE #3429: port: Add Command and CommandResult activity types (#5318)
The changes in [Add Command and CommandResult activity types (#5318)](https://github.com/microsoft/botbuilder-dotnet/pull/5318) may need to be ported to maintain parity with `microsoft/botbuilder-dotnet`.

<blockquote>
Fixes https://github.com/microsoft/botbuilder-dotnet/issues/5282

ToDo:
- add more unit tests
- Workout details of returning Status400BadRequest from NotSupportedException?
</blockquote>

Please review and, if necessary, port the changes.

### PR DESCRIPTION
**Pull request by chon219**
Fixes #3429 

## Description

Added command/commandResult activity types and related triggers.

## Specific Changes

  - Added command/commandResult activity types
  - Added trigger OnCommandActivity/OnCommandResultActivity
  - Implemented onCommand/onCommandResult in ActivityHandler

## Testing

Added tests as well.

### CODE REVIEW

**Review by joshgummersall — APPROVED** [review]

File: libraries/botbuilder-dialogs-adaptive/src/conditions/onCommandActivity.ts [hunk 1]
```diff
@@ -0,0 +1,28 @@
...
+export class OnCommandActivity extends OnActivity {
+    public static $kind = 'Microsoft.OnCommandActivity';
+
+    /**
+     * Intiializes a new instance of the [OnCommandActivity](xref:botbuilder-dialogs-adaptive.OnCommandActivity) class.
+     *
+     * @param actions Optional, list of actions.
+     * @param condition Optional, condition which needs to be met for the actions to be executed.
+     */
+    public constructor(actions?: Dialog[], condition?: string) {
```
Comment (stevengum) [inline libraries/botbuilder-dialogs-adaptive/src/conditions/onCommandActivity.ts:25]: I don't think we use `public` on the constructors, at the very least we're not consistent... @joshgummersall since the default is `public`, what do you want to follow as a policy going forwards?

Comment (joshgummersall) [reply libraries/botbuilder-dialogs-adaptive/src/conditions/onCommandActivity.ts:25]: Sorry - merged this before you had a chance to comment. I'm typically in favor of being terse whenever possible, so I tend to omit `public` since it is the default. I'm open to either, though, and I agree we should use a consistent style.

Comment (stevengum) [reply libraries/botbuilder-dialogs-adaptive/src/conditions/onCommandActivity.ts:25]: Filed https://github.com/microsoft/botbuilder-js/issues/3518 to track removing `public` where unnecessary and adding a corresponding eslint rule.
