### PR TITLE
fix: ignore node_modules declarative assets

### LINKED ISSUE #3710: Ignore node_modules declarative assets in runtime
The gist is that Composer copies declarative assets into `dialogs/imported` when adding a package or scaffolding a new template. Depending on the order of file paths, the Resource Explorer might favor files in `node_modules`. As a result, a running bot would not use the (potentially edited) files that Composer references.

See https://github.com/microsoft/BotFramework-Composer/issues/7916 for more details.

### PR DESCRIPTION
**Pull request by joshgummersall**
Fixes #3710

### CODE REVIEW

File: libraries/botbuilder-dialogs-adaptive-runtime/src/configurationResourceExplorer.ts [hunk 1]
```diff
@@ -2,25 +2,20 @@
...
 
         const applicationRoot = configuration.string(['applicationRoot']);
         ok(applicationRoot);
 
-        this.folderResourceProvider = new FolderResourceProvider(
-            this,
+        this.addFolders(
             applicationRoot,
-            true,
+            ['node_modules'], // Composer copies to `dialogs/imported` so `node_modules` will contain dupes
```
Comment (mdrichardson) [inline libraries/botbuilder-dialogs-adaptive-runtime/src/configurationResourceExplorer.ts:17]: I'm surprised `true` didn't throw before. Should we make [this](https://github.com/microsoft/botbuilder-js/blob/9204b41edf06188fc61518a2b90efd62c6e283f5/libraries/botbuilder-dialogs-declarative/src/resources/resourceExplorer.ts#L144) `ignoreFolders.length`, while we're at it?

I'm not sure what the folder structure looks like, but are there other folders that we'd want to ignore?

Comment (joshgummersall) [reply libraries/botbuilder-dialogs-adaptive-runtime/src/configurationResourceExplorer.ts:17]: We registered folders in a different way before that did not support an `ignore_folders` param. @srinaath verified that this fix solved the problem so I don't think we need to ignore anything else for now.

**Review by mdrichardson — APPROVED** [review]
