### PR TITLE
fix: Bug in orchestratorRecognizer.ts InitializeModel

### LINKED ISSUE #3841: When entity model is available, OrchestratorRecognizer failed to load it

### PR DESCRIPTION
**Pull request by tsuwandy**
Fixes #3841

### CODE REVIEW

**Review by hcyang — COMMENTED** [review]
if (this.scoreEntities) {
entityModelFolder).`);
                if (!orchestrator.load(fullModelFolder, entityModelFolder)) {
                    throw new Error(
                        `Model load failed - model folder ${fullModelFolder}, entity model folder ${entityModelFolder}.`
                        );
                }
            } else {
                if (!orchestrator.load(fullModelFolder)) {
                    throw new Error(`Model load failed - model folder ${fullModelFolder}.`);
                }
            }

**Review by hcyang — APPROVED** [review]

File: libraries/botbuilder-ai-orchestrator/src/orchestratorRecognizer.ts [hunk 1]
```diff
@@ -357,12 +357,16 @@ export class OrchestratorRecognizer extends AdaptiveRecognizer implements Orches
             this.scoreEntities = existsSync(entityModelFolder);
 
             const orchestrator = new oc.Orchestrator();
-            if (this.scoreEntities && !orchestrator.load(fullModelFolder, entityModelFolder)) {
-                throw new Error(
-                    `Model load failed - model folder ${fullModelFolder}, entity model folder ${entityModelFolder}.`
-                );
-            } else if (!orchestrator.load(fullModelFolder)) {
-                throw new Error(`Model load failed - model folder ${fullModelFolder}.`);
+            if (this.scoreEntities) {
```
Comment (joshgummersall) [inline libraries/botbuilder-ai-orchestrator/src/orchestratorRecognizer.ts:360]: Can you add a test for this?

**Review by joshgummersall — APPROVED** [review]
