### PR TITLE
fix createHandoffEvent activity.type & cleanup

### LINKED ISSUE #3242: EventFactory.createHandoffInitiation does not set the Activity.type to "event"
## Versions
What package version of the SDK are you using. `main` & version ^4.11.0

## Describe the bug
EventFactory.createHandoffInitiation does not set the Activity.type to "event", so developers need to manually set the type themselves. This behavior is not the implementation in [C#](https://github.com/microsoft/botbuilder-dotnet/blob/82c9228e893a998faf0a92987f84d96b027529c9/libraries/Microsoft.Bot.Builder/EventFactory.cs#L80), nor does it follow the [principle of least astonishment](https://en.wikipedia.org/wiki/Principle_of_least_astonishment).

### PR DESCRIPTION
**Pull request by stevengum**
Fixes #3242

## Description
Sets the `type` on the returned Activity to `ActivityTypes.Event` in EventFactory.createHandoffEvent()

## Specific Changes
  - Set returned `Activity.type` to `ActivityTypes.Event`
  - Cleanup imports, remove unnecessary cast
  - Add test coverage

## Testing
Updated existing test with coverage for changes.

### CODE REVIEW

File: libraries/botbuilder/src/eventFactory.ts [hunk 1]
```diff
@@ -33,7 +32,7 @@ export class EventFactory {
         const handoffEvent = this.createHandoffEvent(
             HandoffEventNames.InitiateHandoff,
             handoffContext,
-            context.activity.conversation as ConversationAccount // TODO(joshgummersall) why is this necessary?
+            context.activity.conversation
```
Comment (joshgummersall) [inline libraries/botbuilder/src/eventFactory.ts:35]: Does this compile?! Amazing.

**Review by joshgummersall — APPROVED** [review]

File: libraries/botbuilder/src/eventFactory.ts (hunk 1 above)
Comment (stevengum) [reply libraries/botbuilder/src/eventFactory.ts:35]: Yeah! I saw the comment and was confused as well. Don't know why we needed it in the first place....
