### PR TITLE
Customize inputhint of prompt property

### LINKED ISSUE #3195: Can not customize inputhint of prompt property in InputDialog
## Describe the bug
Inputhint of prompt should be set as configurable.

issue reference: https://github.com/microsoft/botbuilder-js/issues/1776#issuecomment-733418246

### PR DESCRIPTION
**Pull request by Danieladu**
Fixes #3195

## Description
Using `expectingInput` while `inputHint` property is not assigned of prompt property in InputDialog. Otherwise, keep it as it is.

### CODE REVIEW

File: libraries/botbuilder-dialogs-adaptive/src/input/inputDialog.ts [hunk 1]
```diff
@@ -359,7 +359,9 @@ export abstract class InputDialog extends Dialog implements InputDialogConfigura
             msg = await this.prompt.bind(dc, dc.state);
         }
 
-        msg.inputHint = InputHints.ExpectingInput;
+        if (typeof msg?.inputHint !== 'string' || !msg.inputHint) {
```
Comment (joshgummersall) [inline libraries/botbuilder-dialogs-adaptive/src/input/inputDialog.ts:362]: I think `if (typeof msg?.inputHint !== 'string')` should cover all the cases, unless `msg.inputHint = ''` should be overridden to `InputHints.ExpectingInput`.

**Review by joshgummersall — APPROVED** [review]
Small possible suggestion, otherwise LGTM.

File: libraries/botbuilder-dialogs-adaptive/src/input/inputDialog.ts (hunk 1 above)
Comment (Danieladu) [reply libraries/botbuilder-dialogs-adaptive/src/input/inputDialog.ts:362]: yes. Empty inputHint should be overridden to the default ExpectingInput. Thanks.
