### PR TITLE
[PORT] Fix WaterfallStepContext to use parent dc properly

### LINKED ISSUE #2162: [PORT] Fix WaterfallStepContext to use parent dc properly
> Port this change from botbuilder-dotnet/master branch:
https://github.com/microsoft/botbuilder-dotnet/pull/3855

fixes #3854 
* cleaned up CreateInnerDC so it is applied consistently
* changed WaterfallStepContext ctor to pass in parent dc.

# Changed projects
* Microsoft.Bot.Builder.Dialogs

### PR DESCRIPTION
**Pull request by denscollo**
Fixes #2162

> Port this change from botbuilder-dotnet/master branch:
> microsoft/botbuilder-dotnet# 3855

## Description
This PR fixes an issue that was causing the [WaterfallStepContext](https://github.com/microsoft/botbuilder-js/blob/master/libraries/botbuilder-dialogs/src/waterfallStepContext.ts#L61) class to not assign the **DataContext** parent correctly.

## Specific Changes
- Update [createInnerDC](https://github.com/microsoft/botbuilder-js/blob/master/libraries/botbuilder-dialogs/src/componentDialog.ts#L246) method to support [DialogContext](https://github.com/microsoft/botbuilder-js/blob/master/libraries/botbuilder-dialogs/src/dialogContext.ts#L56) class as a parameter.
- Update [createChildContext](https://github.com/microsoft/botbuilder-js/blob/master/libraries/botbuilder-dialogs/src/componentDialog.ts#L173) method to support the changes made in the [createInnerDC](https://github.com/microsoft/botbuilder-js/blob/master/libraries/botbuilder-dialogs/src/componentDialog.ts#L246) method.
- Update [WaterfallStepContext](https://github.com/microsoft/botbuilder-js/blob/master/libraries/botbuilder-dialogs/src/waterfallStepContext.ts#L61) class constructor to pass the parent correctly to the inherited class.
- Add unit test to support this changes, located in [waterfallDialog.test.js](https://github.com/microsoft/botbuilder-js/blob/master/libraries/botbuilder-dialogs/tests/waterfallDialog.test.js#L32).

## Testing
In the following images are listed the new **unit tests** and the proper parent inheritance.
image
image

### CODE REVIEW

File: libraries/botbuilder-dialogs/src/componentDialog.ts [hunk 1]
```diff
@@ -243,10 +240,27 @@ export class ComponentDialog<O extends object = {}> extends DialogContainer<O> {
...
-        const innerDC: DialogContext = new DialogContext(this.dialogs, context, dialogState);
+
+        let innerDC: DialogContext;
+
+        if(context instanceof DialogContext){
+            innerDC = new DialogContext(this.dialogs, context, dialogState);
+
+        }else{
+            innerDC = new DialogContext(this.dialogs, context, dialogState);
+        }
```
Comment (stevengum) [inline libraries/botbuilder-dialogs/src/componentDialog.ts:263]: This if-check is unnecessary due to differences in language between C# and TypeScript.

returning a `new DialogContext(this.dialogs, context, dialogState);` should suffice.

File: libraries/botbuilder-dialogs/src/waterfallStepContext.ts [hunk 2]
```diff
@@ -59,9 +59,8 @@ export class WaterfallStepContext<O extends object = {}> extends DialogContext {
      * @param info Values to initialize the step context with.
      */
     constructor(dc: DialogContext, info: WaterfallStepInfo<O>) {
-        super(dc.dialogs, dc.context, { dialogStack: dc.stack });
+        super(dc.dialogs, dc, { dialogStack: dc.stack });
```
Comment (stevengum) [inline libraries/botbuilder-dialogs/src/waterfallStepContext.ts:62]: Can this be reduced to `super(dc)`?

Do we need to manually create the DialogState?

File: libraries/botbuilder-dialogs/tests/waterfallDialog.test.js [hunk 3]
```diff
@@ -634,4 +634,61 @@ describe('WaterfallDialog', function () {
...
+
+            const results = await dc.beginDialog('composite');
+
+            if (results.status === DialogTurnStatus.complete) {
+                const waterfallParent = results.result.parent.parent;
+
+                assert.strictEqual(waterfallParent.dialogs.dialogs['composite'], component, 'WaterfallDialog "waterfall" parent should be equal to ComponentDialog "composite".');
+            }
+
+            done();
```
Comment (stevengum) [inline libraries/botbuilder-dialogs/tests/waterfallDialog.test.js:663]: If the result.status is not DialogTurnStatus.complete, then this test passes because done() is called.

File: libraries/botbuilder-dialogs/tests/waterfallDialog.test.js [hunk 4]
```diff
@@ -634,4 +634,61 @@ describe('WaterfallDialog', function () {
...
+
+        const adapter = new TestAdapter(async turnContext => {
+            const dc = await dialogs.createContext(turnContext);
+            const results = await dc.beginDialog('waterfall');
+
+            if (results.status === DialogTurnStatus.complete) {
+                assert.deepStrictEqual(results.result.parent, dc, 'waterfall parent should be equal to Dialog Context.');
+            }
+
+            done();
```
Comment (stevengum) [inline libraries/botbuilder-dialogs/tests/waterfallDialog.test.js:688]: Same problem around results.status === DialogTurnStatus.complete and the test passing.

**Comment by denscollo** [comment]
@stevengum Feedback applied. Thanks!
