### PR TITLE
fix: correct QnAMaker response types and expose error from server

### LINKED ISSUE #2317: [Adaptive] QnAMakerRecognizer should not error on missing property configuration.
QnAMaker recognizer throws without configuring these other properties. It should not throw my default

```
[onTurnError] unhandled error: TypeError: Cannot read property 'map' of undefined
```
```js
// property path that holds qna context
qnaRecognizer.context = new ObjectExpression("dialog.qnaContext");

// Property path where previous qna id is set. This is required to have multi-turn QnA working.
qnaRecognizer.qnaId = new IntExpression("turn.qnaIdFromPrompt");

// Disable automatically including dialog name as meta data filter on calls to QnA Maker.
qnaRecognizer.includeDialogNameInMetadata = new BoolExpression("false"); 
```

To reproduce, run [this sample][1] without the above configurations (disable in the QnAMakerRecognizer)

[1]:https://github.com/microsoft/BotBuilder-Samples/tree/master/experimental/adaptive-dialog/javascript_nodejs/07.qnamaker

### PR DESCRIPTION
**Pull request by chon219**
Fixes #2317 

## Description

This PR exposed error message from QnAMaker server to allow users locating and fixing errors.
Response type of `HttpRequestUtils` of QnAMaker is not correctly defined, it should be `QnAMakerResults` (while calling `generate` api) or undefined (while calling `train` api).  Check out https://docs.microsoft.com/en-us/rest/api/cognitiveservices/qnamaker4.0/runtime/generateanswer#response . This PR will fix this.

## Specific Changes

  - Exposed error from QnAMaker server side
  - Corrected return type to `QnAMakerResults`
  -

### CODE REVIEW

File: libraries/botbuilder-ai/src/qnamaker-utils/generateAnswerUtils.ts [hunk 1]
```diff
@@ -82,14 +82,18 @@ export class GenerateAnswerUtils {
...
-        const qnaResultJson = await this.httpRequestUtils.executeHttpRequest(
+        const qnaResults = await this.httpRequestUtils.executeHttpRequest(
             url,
             payloadBody,
             this.endpoint,
             queryOptions.timeout
         );
 
-        return this.formatQnaResult(qnaResultJson);
+        if (qnaResults?.answers && Array.isArray(qnaResults.answers)) {
```
Comment (joshgummersall) [inline libraries/botbuilder-ai/src/qnamaker-utils/generateAnswerUtils.ts:92]: These can be collapsed into `if (Array.isArray(qnaResults?.answers)) { ... }`

File: libraries/botbuilder-ai/src/qnamaker-utils/httpRequestUtils.ts [hunk 2]
```diff
@@ -31,14 +31,14 @@ export class HttpRequestUtils {
...
-     * @returns {QnAMakerResult} a promise that resolves to the QnAMakerResult
+     * @returns {QnAMakerResults} a promise that resolves to the QnAMakerResults
      */
     public async executeHttpRequest(
         requestUrl: string,
         payloadBody: string,
         endpoint: QnAMakerEndpoint,
         timeout?: number
-    ): Promise<QnAMakerResult> {
+    ): Promise<QnAMakerResults> {
```
Comment (joshgummersall) [inline libraries/botbuilder-ai/src/qnamaker-utils/httpRequestUtils.ts:41]: This should be amended to include `| undefined` since that's a possible return type.

**Review by joshgummersall — CHANGES_REQUESTED** [review]
Two quick suggestions.

**Review by joshgummersall — APPROVED** [review]
