### PR TITLE
fix: auto-disable telemetry for schema tests

### LINKED ISSUE #3687: BF-CLI telemetry prompt can cause timeout for schema tests
https://github.com/microsoft/botframework-cli#enable-telemetry-in-continuous-integration-pipelines

### PR DESCRIPTION
**Pull request by mdrichardson**
Fixes #3687 

## Description

When installing bf-cli, there is sometimes a prompt during install to allow telemetry.
We need to set an environment variable so the prompt doesn't appear and halt install, causing a timeout.

See: https://github.com/microsoft/botframework-cli#enable-telemetry-in-continuous-integration-pipelines

### CODE REVIEW

File: libraries/botbuilder-dialogs-declarative/tests/schemaMergeTest.js [hunk 1]
```diff
@@ -64,6 +64,13 @@ describe('Schema Merge Tests', function () {
             // Try installing latest bf if the schema changed to make sure the
             // discrepancy is not because we are using a different version of the CLI
             // and we ensure it is installed while on it.
+
+            // When installing bf-cli, there is sometimes a prompt during install to allow telemetry.
+            // We need to set an environment variable so the prompt doesn't appear and halt install, causing a timeout.
+            const telemSettingPath = 'BF_CLI_TELEMETRY';
+            const originalTelemSetting = process.env[telemSettingPath];
+            process.env[telemSettingPath] = false;
```
Comment (joshgummersall) [inline libraries/botbuilder-dialogs-declarative/tests/schemaMergeTest.js:72]: There's actually a way to [pass a custom set of environment variables](https://nodejs.org/api/child_process.html#child_process_child_process_exec_command_options_callback) when calling `exec`. In my opinion, it's a little cleaner as you aren't trouncing any global state. It also makes clear where this side effect is necessary.

Comment (mdrichardson) [reply libraries/botbuilder-dialogs-declarative/tests/schemaMergeTest.js:72]: Ah, I forgot about that! Making the adjustment, now.

**Review by joshgummersall — APPROVED** [review]
Beauty!
