### PR TITLE
[PORT]Fix Random thread safety and control random seed to improve testability

### LINKED ISSUE #2727: [PORT] Fix Random thread safety and control random seed to improve testability
> Port this change from botbuilder-dotnet/master branch:
https://github.com/microsoft/botbuilder-dotnet/pull/4429

Fixes #4361

## Description
This PR aims to accept a "Microsoft.SetTestOptions" event, and apply the options to SDK.

## Specific Changes
1. Add `setTestOptions` event
2. Save TestOptions into the conversation state. Including the Random seed and random value.
3. Achieve the state from "dialogContext.State", and apply it to SDK code.
4. Adjust random generator code to use the random in "TestOptions".

## How to test
1. Start project "Microsoft.Bot.Builder.TestBot.Json"
2. Input 26 to see the dialog output.

## Progress
- [x] Adaptive-expression
- [x] LG Evaluator/Expander
- [x] Random selector

# Changed projects
* AdaptiveExpressions
* Microsoft.Bot.Builder.Dialogs.Adaptive.Testing
* Microsoft.Bot.Builder.Dialogs.Adaptive
* Microsoft.Bot.Builder.LanguageGeneration
* AdaptiveExpressions.Tests
* Microsoft.Bot.Builder.Dialogs.Adaptive.Tests
* Microsoft.Bot.Builder.TestBot.Json
*

### PR DESCRIPTION
**Pull request by Danieladu**
Fixes #2727
## Description
This PR aims to accept a "Microsoft.SetTestOptions" event, and apply the options to SDK.

## Specific Changes
1. Add `setTestOptions` event
2. Save TestOptions into the conversation state. Including the random value.
3. Achieve the state from "dialogContext.State", and apply it to SDK code.
4. Adjust random generator code to use the random in "TestOptions".

## Progress
- [x] Adaptive-expression
- [x] LG Evaluator/Expander
- [x] Random selector

### CODE REVIEW

File: libraries/adaptive-expressions/src/builtinFunctions/rand.ts [hunk 1]
```diff
@@ -19,22 +23,37 @@ export class Rand extends ExpressionEvaluator {
...
-            }
+    private static evaluator(expression: Expression, state: MemoryInterface, options: Options): ValueWithError {
+        let result;
+        let minValue;
+        let maxValue;
+        let error: string;
+
+        ({ value: minValue, error } = expression.children[0].tryEvaluate(state, options));
+        if (error) {
+            return { value: result, error };
```
Comment (joshgummersall) [inline libraries/adaptive-expressions/src/builtinFunctions/rand.ts:37]: It's strange to return `result` intentionally before initialization. Omitting `value` here should yield the same effect: an `undefined` value.

File: libraries/adaptive-expressions/src/builtinFunctions/rand.ts [hunk 2]
```diff
@@ -19,22 +23,37 @@ export class Rand extends ExpressionEvaluator {
...
-            if (args[0] > args[1]) {
-                error = `Min value ${args[0]} cannot be greater than max value ${args[1]}.`;
-            }
+    private static evaluator(expression: Expression, state: MemoryInterface, options: Options): ValueWithError {
+        let result;
+        let minValue;
+        let maxValue;
+        let error: string;
+
+        ({ value: minValue, error } = expression.children[0].tryEvaluate(state, options));
```
Comment (joshgummersall) [inline libraries/adaptive-expressions/src/builtinFunctions/rand.ts:35]: I think it reads cleaner to extract these child values before using them:

```typescript
const [maybeMinValue, maybeMaxValue] = expression.children;
...
... = maybeMinValue.tryEvaluate(state, options);
```

Comment (joshgummersall) [reply libraries/adaptive-expressions/src/builtinFunctions/rand.ts:35]: Some type checking may be useful as well, though I'm not sure if that's the convention in `adaptive-expressions`.

File: libraries/botbuilder-dialogs-adaptive-testing/src/setTestOptionsMiddleware.ts [hunk 3]
```diff
@@ -0,0 +1,31 @@
...
+     */
+    public async onTurn(context: TurnContext, next: () => Promise<void>): Promise<void> {
+        if (context.activity.type === ActivityTypes.Event) {
+            if (context.activity.name === 'SetTestOptions') {
+                const conversationState = context.turnState.get(CONVERSATION_STATE);
+                const property = conversationState.createProperty('TestOptions');
+                await property.set(context, context.activity.value);
+            }
+        }
+        if (next) {
```
Comment (joshgummersall) [inline libraries/botbuilder-dialogs-adaptive-testing/src/setTestOptionsMiddleware.ts:27]: Is `next` allowed to be falsy? If so, make sure to change the method signature to account for this.

File: libraries/botbuilder-dialogs-adaptive-testing/src/testActions/customEvent.ts [hunk 4]
```diff
@@ -0,0 +1,40 @@
...
+    public static $kind = 'Microsoft.Test.CustomEvent';
+    /**
+     * The event name.
+     */
+    public name: string;
+
+    /**
+     * Event value.
+     */
+    public value: unknown;
```
Comment (joshgummersall) [inline libraries/botbuilder-dialogs-adaptive-testing/src/testActions/customEvent.ts:27]: You could consider extracting a type parameter for this rather than hardcoding `unknown`. Up to you, though.

**Review by joshgummersall — CHANGES_REQUESTED** [review]
Left a few suggestions, otherwise looks good!

File: libraries/botbuilder-dialogs-adaptive-testing/src/testActions/customEvent.ts (hunk 4 above)
Comment (Danieladu) [reply libraries/botbuilder-dialogs-adaptive-testing/src/testActions/customEvent.ts]: Actually, there is no type of limitation on property `value`.  Is there any good idea?

File: libraries/botbuilder-dialogs-adaptive-testing/src/setTestOptionsMiddleware.ts [hunk 5]
```diff
@@ -0,0 +1,31 @@
...
+
+const CONVERSATION_STATE = 'ConversationState';
+
+export class SetTestOptionsMiddleware implements Middleware {
+    /**
+     * Processes an incoming event activity.
+     * @param context The context object for this turn.
+     * @param next The delegate to call to continue the bot middleware pipeline
+     */
+    public async onTurn(context: TurnContext, next: () => Promise<void>): Promise<void> {
```
Comment (joshgummersall) [inline libraries/botbuilder-dialogs-adaptive-testing/src/setTestOptionsMiddleware.ts:19]: I meant that 'next' should be marked as an optional (?) parameter here. Otherwise, the null check below doesn't make sense.

Comment (Danieladu) [reply libraries/botbuilder-dialogs-adaptive-testing/src/setTestOptionsMiddleware.ts:19]: `onTurn` is defined in the interface "Middleware", and the next parameter is required.
But the required `next` is may still be assigned to `null`, for example:
```
const middleware = new SetTestOptionsMiddleware();
middleware.onTurn(context, null); //This is allowed by the typescript compiler
```

Comment (joshgummersall) [reply libraries/botbuilder-dialogs-adaptive-testing/src/setTestOptionsMiddleware.ts:19]: It should not compile, [see this Typescript playground example](https://www.typescriptlang.org/play?#code/MYewdgzgLgBAZgVzMGBeGAKAhgLkwSjQD4YA3EASwBNDUSBvAKBhZiw3wG5GBfRxxMgxgEAG1FcgA).

The compiler settings must be too permissive at the moment, i.e., not using `strictNullChecks`. You should either change the signature to make `next` optional or remove the `if` check (and optionally throw a `TypeError` if next is not defined).

As time permits, we will invest in making our Typescript code more correct by enabling more strict compilation settings. There's no reason to write code now that doesn't conform to those stricter standards.

Comment (Danieladu) [reply libraries/botbuilder-dialogs-adaptive-testing/src/setTestOptionsMiddleware.ts:19]: It is strange that there is no error in my vscode. Hmmm.

Comment (joshgummersall) [reply libraries/botbuilder-dialogs-adaptive-testing/src/setTestOptionsMiddleware.ts:19]: I think setting `strictNullChecks` (or, preferably, just `strict`) to `true` in the `tsconfig.json` file would do the trick.

File: libraries/botbuilder-dialogs-adaptive-testing/src/testActions/customEvent.ts [hunk 6]
```diff
@@ -0,0 +1,40 @@
...
+
+import { TurnContext, TestAdapter, ActivityTypes } from 'botbuilder-core';
+import { TestAction } from '../testAction';
+
+export interface CustomEventConfiguration {
+    name: string;
+    value?: unknown;
+}
+
+export class CustomEvent extends TestAction implements CustomEventConfiguration {
```
Comment (joshgummersall) [inline libraries/botbuilder-dialogs-adaptive-testing/src/testActions/customEvent.ts:17]: If you change this class declaration to:

```typescript
export class CustomEvent<T = unknown> extends TestAction implements CustomEventConfiguration {
  ...
  value: T;
}
```

That opens up the ability for users to strongly type instances of the `CustomEvent` class but supports a useful default of `unknown`.

**Review by joshgummersall — CHANGES_REQUESTED** [review]
One last suggestion around typing.

**Review by joshgummersall — APPROVED** [review]
