### PR TITLE
Compute LG SourceRange based on content instead of parsed token

### LINKED ISSUE #3076: lg update template to the wrong position.
## Versions
What package version of the SDK are you using.
What nodejs version are you using
What browser version are you using
What os are you using

## Describe the bug
Give a clear and concise description of what the bug is.

## To Reproduce
1. Prepare a lg file with content：
```
# Exit
-Thanks for using todo bot.

# Greeting
-What's up bro
```

2. update `#Exit` with body
```
-Thanks for using todo bot.
- Bye.
                 // notice here is a new line
```

3. use step2 returned `resource`, continue do update on `#Greeting` with body
```
-Hi
``` 

4. See LG file will be updated to 
```
# Exit
-Thanks for using todo bot.
- Bye.

# Greeting
-Hi
-What's up bro   // this line should be replaced.
```

with more investigate, we find after step2, in returned `resource`, all templates below `#Exit`  source range is not be updated. it should have offset, cause step2 add a  new line, the template after it should also update it's source range.

## Expected behavior
Give a clear and concise description of what you expected to happen.

### PR DESCRIPTION
**Pull request by Danieladu**
Fixes #3076

### Root cause
Previously, the sourceRange(start and end line position) of a LG template is calculated based on the parsed token. But in certain scenarios that, when there are extra empty character (line breaks) at the end of a template, will cause this calculation not correct, and thus causing the further update on this lg file misplaced in the wrong position, causing potential data loss. 

### Fix
Use the real content received to calculate start\end line.  Content is the golden truth, more trustworthy than parsed tokens. 

### Impact
Composer

### CODE REVIEW

File: libraries/botbuilder-lg/src/templates.ts [hunk 1]
```diff
@@ -567,6 +572,19 @@ export class Templates implements Iterable<Template> {
         return destList.join(this.newLine);
     }
 
+    /**
+     * @private
+     */
+    private adjustSingleTemplateRange(template: Template, content: string): Template {
```
Comment (boydc2014) [inline libraries/botbuilder-lg/src/templates.ts:578]: Rename to recomputeSourceRange

File: libraries/botbuilder-lg/src/templates.ts [hunk 2]
```diff
@@ -406,8 +407,12 @@ export class Templates implements Iterable<Template> {
         this.appendDiagnosticWithOffset(updatedTemplates.diagnostics, originalStartLine);
 
         if (updatedTemplates.toArray().length > 0) {
-            const newTemplate = updatedTemplates.toArray()[0];
+            const newTemplate = this.adjustSingleTemplateRange(updatedTemplates.toArray()[0], content);
             this.adjustRangeForAddTemplate(newTemplate, originalStartLine);
+
+            // adjust the previous range
```
Comment (boydc2014) [inline libraries/botbuilder-lg/src/templates.ts:413]: adjust the last template's range when adding the template

File: libraries/botbuilder-lg/src/templates.ts [hunk 3]
```diff
@@ -406,8 +407,12 @@ export class Templates implements Iterable<Template> {
...
+            this.items[this.items.length - 1].sourceRange.range.end.line = newTemplate.sourceRange.range.start.line - 1;
```
Comment (boydc2014) [inline libraries/botbuilder-lg/src/templates.ts:414]: check index overflow?

**Review by boydc2014 — APPROVED** [review]
