### PR TITLE
Fixed a typo in skill extensions

### LINKED ISSUE #2580: Typo in Skill Extensions
TYPO: SkillExtensions.useSkillConverationIdFactory()
Should be SkillExtensions.useSkillConver**s**ationIdFactory()

[bug]

### PR DESCRIPTION
**Pull request by chon219**
Fixes #2580 

## Description

Fixed a typo in skill extensions.

## Specific Changes

  - useSkillConverationIdFactory -> useSkillConversationIdFactory
  -
  -

### CODE REVIEW

File: libraries/botbuilder-dialogs-adaptive/src/skillExtensions.ts [hunk 1]
```diff
@@ -24,7 +34,7 @@ export class SkillExtensions {
     /**
      * Configures the skill conversation id factory to use.
      */
-    public static useSkillConverationIdFactory(dialogManager: DialogManager, skillConversationIdFactory: SkillConversationIdFactoryBase): DialogManager {
+    public static useSkillConversationIdFactory(dialogManager: DialogManager, skillConversationIdFactory: SkillConversationIdFactoryBase): DialogManager {
```
Comment (stevengum) [inline libraries/botbuilder-dialogs-adaptive/src/skillExtensions.ts:37]: Can you add the parameters to the docstring?

Comment (chon219) [reply libraries/botbuilder-dialogs-adaptive/src/skillExtensions.ts:37]: OK, I'll add that.
