### PR TITLE
fix: config file overrides

### LINKED ISSUE #3659: Support config file overrides
We need to essentially rearrange files so that composer generated configs take precedence over appsettings.

### PR DESCRIPTION
**Pull request by joshgummersall**
Fixes #3659

### CODE REVIEW

**Review by stevengum — APPROVED** [review]

File: libraries/botbuilder-dialogs-adaptive-runtime/src/index.ts [hunk 1]
```diff
@@ -374,12 +375,12 @@ function addComposerConfiguration(configuration: Configuration): void {
         environment = userName;
     }
 
-    configuration.file(path.join(botRoot, 'generated', `luis.settings.${environment}.${luisRegion}.json`));
+    configuration.file(path.join(botRoot, 'generated', `luis.settings.${environment}.${luisRegion}.json`), true);
```
Comment (benbrown) [inline libraries/botbuilder-dialogs-adaptive-runtime/src/index.ts:378]: is there ever a case where we want this parameter to be false?
why not make it the default or only behavior?

Comment (joshgummersall) [reply libraries/botbuilder-dialogs-adaptive-runtime/src/index.ts:378]: The underlying library defaults to the opposite behavior (hence the gnarly splice code). I want this behavior to be opt-in only so we can try to be consistent with the underlying library.
