### PR TITLE
Include dialogContext in errors

### LINKED ISSUE #2478: [PORT] Emit better error messages for all dialogs
> Port this change from botbuilder-dotnet/master branch:
https://github.com/microsoft/botbuilder-dotnet/pull/4153

Fixes #3980 

## Description
Change dialogContext to capture exceptions and annotate exception with contextual information about where the exception happened.

## Specific Changes
* Add try/catch handlers to dialogContext methods to set Exception.Data["dialogContext'] with metadata about the context that the exception was thrown.

## Testing
* Updated existing OnError testing to test and validate for the dialog context data 

### Example exception metadata
```
{
   ...,
   "data": 
  {
       "DialogContext": 
       {
            "ActiveDialog": "SetProperty[=`foo`]",
            "Parent": "innerDialog",
           "Stack": [
               "SetProperty[=`foo`]",
               "innerDialog",
               "planningTest"
           ],
       }
}
```

# Changed projects
* Microsoft.Bot.Builder.Dialogs
* Microsoft.Bot.Builder.Dialogs.Tests

### PR DESCRIPTION
**Pull request by joshgummersall**
- Export a DialogContextError type that includes some dialog context
- Wrap async operations in dialogContext to ensure DialogContextError is
thrown
- Add some assertions to tests to ensure error wrapping works properly

Fixes #2478

Sample exception generated using [multi-turn prompt](https://github.com/microsoft/BotBuilder-Samples/tree/main/samples/javascript_nodejs/05.multi-turn-prompt) sample linked against this branch locally. The `onTurnError` handler ads a `JSON.stringify(error, null, 2)` to log all the extra properties.

```
 [onTurnError] unhandled error: {
  "name": "DialogContextError",
  "dialogContext": {
    "activeDialog": "WATERFALL_DIALOG",
    "parent": "userProfileDialog",
    "stack": [
      {
        "id": "WATERFALL_DIALOG",
        "state": {
          "options": {},
          "values": {
            "instanceId": "9a8d01d5-9e2f-055a-c953-6b1f277b8fa0",
            "transport": "Car",
            "name": "josh"
          },
          "stepIndex": 3
        }
      }
    ]
  }
}
```

With Typescript types, one can now do this in a type safe way:

```
import { DialogContextError } from 'botbuilder-dialogs';

const onTurnErrorHandler = async (context, error) => {
    if (error instanceof DialogContextError) {
        const {dialogContext: {
            activeDialog,
            parent,
            stack,
        }} = error;

        console.error({activeDialog, parent, stack})
    }
}
```

## Testing
Added some assertions to existing tests to ensure extra context exists

### CODE REVIEW

File: libraries/botbuilder-dialogs/src/dialogContextError.ts [hunk 1]
```diff
@@ -0,0 +1,37 @@
+import { DialogContext } from './dialogContext';
```
Comment (stevengum) [inline libraries/botbuilder-dialogs/src/dialogContextError.ts:1]: Missing license headers

File: libraries/botbuilder-dialogs/src/dialogContextError.ts [hunk 2]
```diff
@@ -0,0 +1,37 @@
...
+import { DialogInstance } from './dialog';
+
+/**
+ * An Error that includes extra dialog context, including the dialog stack
+ */
+export class DialogContextError extends Error {
+    public readonly dialogContext: {
```
Comment (stevengum) [inline libraries/botbuilder-dialogs/src/dialogContextError.ts:8]: This will need a docstring to avoid eslint errors 😄

File: libraries/botbuilder-dialogs/src/dialogContextError.ts [hunk 3]
```diff
@@ -0,0 +1,37 @@
...
+        parent?: string;
+        stack: DialogInstance[];
+    };
+
+    /**
+     * Construct a DialogError
+     * @param error Source error
+     * @param dialogContext Dialog context that is the source of the error
+     */
+    constructor(source: Error | string, dialogContext: DialogContext) {
```
Comment (stevengum) [inline libraries/botbuilder-dialogs/src/dialogContextError.ts:19]: Because the SDK targets JS and TS developers and this is a public class, the `source` and `dialogContext` parameters should have falsy checks.

**Review by stevengum — CHANGES_REQUESTED** [review]
There were some small things that needed to be addressed, but the DialogContextError constructor needs falsy checks for its parameters.

I do like the approach you've taken here, but @johnataylor should also take a pass at this PR for his perspective on error subclassing.

**Review by stevengum — APPROVED** [review]
Sorry for the delay, LGTM
