### PR TITLE
fix: named pipe issues

### LINKED ISSUE #3472: Nodejs process periodic restart causing "Already connected" error from app service and 502 error from frontend
## Versions
What package version of the SDK are you using - 4.10
What nodejs version are you using - v12.18.3

## Describe the bug
We deployed a simple nodejs bot with directline app service extension to Azure app services.
The bot seems to be triggered by some unknown event that causes the node js process to restart at the **exact same time every day (UTC 07:23:39)** 
After the event the bot stops responding and requires a manual restart to resume operation.
From application insights, an "Already connected" error message is thrown by the "PayloadReceiver.connect" method.
From the frontend UI where the bot is called, an 502 error is thrown to the Chrome console.

## Expected behavior
The bot / node js process should not hang or restart periodically

## Additional context
**Bot name** 
apje13svc0002cb9bot

**Callstack as below -** 
Error:
   at PayloadReceiver.connect (at PayloadReceiver.connect (D:\home\site\wwwroot\node_modules\botframework-streaming\lib\payloadTransport\payloadReceiver.js:29:19)at PayloadReceiver.connect (D:\home\site\wwwroot\node_modules\botframework-streaming\lib\payloadTransport\payloadReceiver.js:29:19): D:\home\site\wwwroot\node_modules\botframework-streaming\lib\payloadTransport\payloadReceiver.jsat PayloadReceiver.connect (D:\home\site\wwwroot\node_modules\botframework-streaming\lib\payloadTransport\payloadReceiver.js:29:19): 29)
   at Server._incomingServer.createNodeServer_1.createNodeServer (at Server._incomingServer.createNodeServer_1.createNodeServer (D:\home\site\wwwroot\node_modules\botframework-streaming\lib\namedPipe\namedPipeServer.js:66:36)at Server._incomingServer.createNodeServer_1.createNodeServer (D:\home\site\wwwroot\node_modules\botframework-streaming\lib\namedPipe\namedPipeServer.js:66:36): D:\home\site\wwwroot\node_modules\botframework-streaming\lib\namedPipe\namedPipeServer.jsat Server._incomingServer.createNodeServer_1.createNodeServer (D:\home\site\wwwroot\node_modules\botframework-streaming\lib\namedPipe\namedPipeServer.js:66:36): 66)
   at Server.emit (at Server.emit (events.js:182:13)at Server.emit (events.js:182:13): events.jsat Server.emit (events.js:182:13): 182)
   at Pipe.onconnection (at Pipe.onconnection (net.js:1519:8)at Pipe.onconnection (net.js:1519:8): net.jsat Pipe.onconnection (net.js:1519:8): 1519)

### PR DESCRIPTION
**Pull request by joshgummersall**
- Remove unnecessary autoReconnect logic
- Simplify connection management
- Properly support client reconnection to incoming/outgoing servers

Fixes #3472

### CODE REVIEW

**Comment by joshgummersall** [comment]
Note: this is marked as a draft while we work to ensure this resolves the issue.

File: libraries/botframework-streaming/src/namedPipe/namedPipeServer.ts [hunk 1]
```diff
@@ -70,36 +61,44 @@ export class NamedPipeServer implements IStreamingTransportServer {
...
      */
     public async start(): Promise<string> {
-        if (this._receiver.isConnected || this._sender.isConnected || this._incomingServer || this._outgoingServer) {
-            this.disconnect();
-        }
+        const { PipePath, ServerIncomingPath, ServerOutgoingPath } = NamedPipeTransport;
+
+        const incoming = new Promise<void>((resolve, reject) => {
+            const server = createNodeServer((socket) => {
+                if (this._receiver.isConnected) {
```
Comment (joshgummersall) [inline libraries/botframework-streaming/src/namedPipe/namedPipeServer.ts:68]: This skips the connect logic for subsequent connections without terminating the underlying socket. My gut says it's bad to hold sockets open that aren't in use, but I don't know how Directline ASE/IISNode works with multiple Node procs and connections. A little wisdom here would be helpful!

File: libraries/botframework-streaming/src/namedPipe/namedPipeServer.ts [hunk 2]
```diff
@@ -70,36 +61,44 @@ export class NamedPipeServer implements IStreamingTransportServer {
...
+            server.listen(PipePath + this.baseName + ServerIncomingPath);
+
+            this._incomingServer = server;
         });
 
-        const outgoing = new Promise((resolve) => {
-            this._outgoingServer = createNodeServer((socket: INodeSocket): void => {
+        const outgoing = new Promise<void>((resolve, reject) => {
+            const server = createNodeServer((socket) => {
+                if (this._sender.isConnected) {
```
Comment (joshgummersall) [inline libraries/botframework-streaming/src/namedPipe/namedPipeServer.ts:84]: Same note with regard to skipping subsequent connections.

File: libraries/botframework-streaming/src/namedPipe/namedPipeServer.ts (hunk 1 above)
Comment (DDEfromOR) [reply libraries/botframework-streaming/src/namedPipe/namedPipeServer.ts:68]: I like this! I think the previous implementation was an artifact of the original code being written by a C# engineer stumbling through writing a TypeScript library (me) and failing to make proper use of promises.

File: libraries/botframework-streaming/src/payloadTransport/payloadSender.ts [hunk 3]
```diff
@@ -37,15 +38,15 @@ export class PayloadSender {
...
+        this._sender = sender;
     }
 
     /**
      * Sends a payload out over the connected transport sender.
      *
      * @param header The header to attach to the outgoing payload.
      * @param payload The stream of buffered data to send.
-     * @param sentCalback The function to execute when the send has completed.
+     * @param sentCallback The function to execute when the send has completed.
```
Comment (DDEfromOR) [inline libraries/botframework-streaming/src/payloadTransport/payloadSender.ts:49]: Nice catch!

**Review by DDEfromOR — APPROVED** [review]
Solid improvements, thank you Josh!

**Comment by joshgummersall** [comment]
This has been running stable in a sample bot for >24 hours so I think it's safe to say it works.

File: libraries/botframework-streaming/src/namedPipe/namedPipeServer.ts [hunk 4]
```diff
@@ -20,48 +20,39 @@ import { createNodeServer } from '../utilities/createNodeServer';
...
-    private readonly _autoReconnect: boolean;
-    private _isDisconnecting: boolean;
 
     /**
      * Creates a new instance of the [NamedPipeServer](xref:botframework-streaming.NamedPipeServer) class.
      *
      * @param baseName The named pipe to connect to.
      * @param requestHandler Optional [RequestHandler](xref:botframework-streaming.RequestHandler) to process incoming messages received by this client.
-     * @param autoReconnect Optional setting to determine if the client should attempt to reconnect automatically on disconnection events. Defaults to true.
+     * @param autoReconnect Optional flag to indicate that server should reconnect instead of closing
```
Comment (mdrichardson) [inline libraries/botframework-streaming/src/namedPipe/namedPipeServer.ts:33]: Do we have a convention for deprecating arguments? I think pre-fixing the `@param` description with `DEPRECATED:` (or similar) would be nice so that developers can avoid the `console.warn` prematurely through intellisense.

**Comment by joshgummersall** [comment]
A bot running with this code actually did reproduce the customer issue. Let's hold off on this (converting back to a draft for now).

File: libraries/botframework-streaming/src/namedPipe/namedPipeServer.ts (hunk 4 above)
Comment (joshgummersall) [reply libraries/botframework-streaming/src/namedPipe/namedPipeServer.ts:33]: It seems [JSDoc does not support this](https://stackoverflow.com/questions/29763919/jsdoc-param-together-with-deprecated), so I'll opt for including `Deprecated: ` in the description. Good call!

File: libraries/botframework-streaming/src/utilities/createNodeServer.ts [hunk 5]
```diff
@@ -8,39 +8,54 @@
...
+/**
+ * Create a Node 'net' server
+ *
+ * @param callback Optional connection listener
+ * @returns a Node 'net' server instance
+ */
+export function createNodeServer(callback?: ConnectionListener): INodeServer {
     if (callback && typeof callback !== 'function') {
-        throw new TypeError(`Invalid callback; callback parameter must be a function to create Node 'net' Server.`);
+        throw new TypeError("Invalid callback; callback parameter must be a function to create Node 'net' Server.");
```
Comment (stevengum) [inline libraries/botframework-streaming/src/utilities/createNodeServer.ts:21]: Is this a lint rule or personal preference? If the latter, we should align on the pattern, codify it and add it to the repo.

**Review by stevengum — APPROVED** [review]

File: libraries/botframework-streaming/src/utilities/createNodeServer.ts (hunk 5 above)
Comment (joshgummersall) [reply libraries/botframework-streaming/src/utilities/createNodeServer.ts:21]: We should probably eslint this - IMO backticks should be reserved for templating.

Comment (stevengum) [reply libraries/botframework-streaming/src/utilities/createNodeServer.ts:21]: Filed https://github.com/microsoft/botbuilder-js/issues/3685

File: libraries/botframework-streaming/src/namedPipe/namedPipeServer.ts [hunk 6]
```diff
@@ -58,42 +58,42 @@ export class NamedPipeServer implements IStreamingTransportServer {
...
+                this._receiver.connect(new NamedPipeTransport(socket));
+            }).once('error', reject);
 
-                server.once('error', (err) => {
-                    rejectListening(err);
-                    rejectClosed(err);
-                });
+            const listening = new Promise<void>((resolve, reject) => {
+                this._incomingServer.once('closed', resolve);
+                this._incomingServer.once('error', reject);
```
Comment (stevengum) [inline libraries/botframework-streaming/src/namedPipe/namedPipeServer.ts]: tiny nit: it would be easier on the eyes if the `resolve` and `reject` of the inner promise had different names than the outer promise.

(not blocking)

**Review by stevengum — APPROVED** [review]
Approving again for the latest commits (https://github.com/microsoft/botbuilder-js/pull/3627/commits/101c4ecd7bb9953379c52f4cd52de35b19a22176, https://github.com/microsoft/botbuilder-js/pull/3627/commits/bb7ea8135dc62f759bfca5a2872213f2189d146a).

There was one small bit of feedback around naming, but the changes in this PR make the code in around NamedPipes much, _much_ clearer. Great work!
