### PR TITLE
Catch errors in ShowTypingMiddleware

### LINKED ISSUE #2527: ShowTypingMiddleware should have better error handling
## Versions
NodeJS v10.15.3
BotBuilder NodeJS SDK v4.9.2
My app is written is typescript

## Describe the bug
ShowTypingMiddleware errors cannot be handled by onTurnError since it's running inside a setTimeout

## To Reproduce
Every error (usually socket hang up) generated from "await context.adapter.sendActivities" will cause an unhandled exception

## Expected behavior
Better error handling, maybe pass an error handler to the ShowTypingMiddleware constructor

## Additional context
Our app restarts on every unhandled exception so we can't use this middleware until this is fixed

### PR DESCRIPTION
**Pull request by joshgummersall**
Fixes #2527

## Description
This fixes the bug described in the linked issue. In particular, errors are now caught and passed to the error handler registered on the adapter, if it exists.

## Specific Changes
* Small refactoring to leverage more idiomatic Typescript and Javascript (inline class constructor params, leverage inferred types, use proper `setTimeout` type, arrow functions for `this` propagation, etc)
* Catch errors in ShowTypingMiddleware `setTimeout` function
* Add a test to verify this behavior

## Testing
* Added a test to verify behavior.

### CODE REVIEW

File: libraries/botbuilder-core/src/showTypingMiddleware.ts [hunk 1]
```diff
@@ -20,104 +20,65 @@ import { TurnContext } from './turnContext';
...
-                        // Do nothing! This turn is done and we don't want to continue sending typing indicators.
+        let timeout: ReturnType<typeof setTimeout>;
+
+        const scheduleIndicator = (delay = this.delay) => {
+            timeout = setTimeout(async () => {
+                if (!finished) {
+                    try {
+                        await this.sendTypingActivity(context);
+                    } catch (err) {
+                        await context.adapter.onTurnError(context, err);
```
Comment (EricDahlvang) [inline libraries/botbuilder-core/src/showTypingMiddleware.ts:52]: I'm not sure onTurnError is guaranteed to have a value?

Comment (joshgummersall) [reply libraries/botbuilder-core/src/showTypingMiddleware.ts:52]: Good point, can we default it to `console.error(err)` or something of the sort? We can certainly only invoke it conditionally, I'm not sure how strict our parity requirement are around things like this.

Comment (stevengum) [reply libraries/botbuilder-core/src/showTypingMiddleware.ts]: The latest [changes](https://github.com/microsoft/botbuilder-js/pull/2786/commits/bcfe26a4c7daa88bc3b16eb98b931cdef156933d#diff-5b9f058c68a2725e35cba9c53da4d2f4R52-R56) make it so that if the adapter doesn't have an onTurnError, it's going to result in an uncaught exception:

https://github.com/microsoft/botbuilder-js/blob/bcfe26a4c7daa88bc3b16eb98b931cdef156933d/libraries/botbuilder-core/src/showTypingMiddleware.ts#L51-L57

Theoretically speaking, those caring about uncaught exceptions will likely have an onTurnError, but others may still stray down the no `Adapter.onTurnError` path and end up with the same result described in issue #2527. 

___

The ShowTypingMiddleware constructors are the same between .NET, JS and Python; `constructor(delay: number, period: number)`. Ideally through either the constructor or public setters, we would have a settable `TelemetryClient` and/or an `ILogger` (.NET specific) that we could call when Adapter.OnTurnError is falsy.

Can you add a test for the missing `onTurnError` path?

**Review by stevengum — CHANGES_REQUESTED** [review]
Please see feedback via https://github.com/microsoft/botbuilder-js/pull/2786#discussion_r493860826 and consider adding a BotTelemetryClient property to the ShowTypingMiddleware class.

File: libraries/botbuilder-core/src/showTypingMiddleware.ts (hunk 1 above)
Comment (joshgummersall) [reply libraries/botbuilder-core/src/showTypingMiddleware.ts]: @stevengum this is intentional - (as far as I can tell) the current behavior for a Bot without an `onTurnError` handler is Promise rejection ([looking at this code](https://github.com/microsoft/botbuilder-js/blob/master/libraries/botbuilder-core/src/botAdapter.ts#L170)). Eventually (again, as far as I can tell), that Promise rejection is bubbled up as an UnhandledPromiseRejectionWarning. I'm not as well versed in the error handling across the board, so if it is indeed customary to mask/swallow errors then I'll relent, though I'll register some intuition that says masking errors is potentially problematic.

Comment (stevengum) [reply libraries/botbuilder-core/src/showTypingMiddleware.ts]: Good point! This is almost certainly a non-scenario because we by default make all samples and generators/templates have an onTurnError. A developer would need to start from nothing to have non-negligible chances of not having an onTurnError.

The only reason we would potentially swallow the error is because it's (debatably) a non-critical operation from the bot. I'd prefer if we at least sent a trace to the App Insights indicating that an error occurred when trying to send a typing activity via a BotTelemetryClient, but that's out of scope and rethrowing the error is fine.

**Comment by joshgummersall** [comment]
@stevengum I think we are good to go, provided we are okay with the error handling tradeoffs discussed above.

**Review by stevengum — APPROVED** [review]
