### PR TITLE
Fix AppCredentials compilation error in BotFrameworkAdapter

### LINKED ISSUE #1901: [BotBuilder][4.8] Compilation error due to different AppCredential used
## Versions
What package version of the SDK are you using.
[4.8.0](https://botbuilder.myget.org/feed/botbuilder-v4-js-daily/package/npm/botbuilder/4.8.0) from MyGet
What nodejs version are you using
10.8.0
What browser version are you using
\-
What os are you using
Windows 10

## Describe the bug
Give a clear and concise description of what the bug is.
Using [4.8.0](https://botbuilder.myget.org/feed/botbuilder-v4-js-daily/package/npm/botbuilder/4.8.0) of botbuilder's packages from MyGet, it throws a **compilation's error**.

This error shows up as `AppCredentials` of the method `exchangeToken` in [BotFrameworkAdapter](https://github.com/microsoft/botbuilder-js/blob/master/libraries/botbuilder/src/botFrameworkAdapter.ts#L712) and [ExtendedUserTokenProvider](https://github.com/microsoft/botbuilder-js/blob/master/libraries/botbuilder-core/src/extendedUserTokenProvider.ts#L94) are different.

`BotFrameworkAdapter` uses [AppCredentials](https://github.com/microsoft/botbuilder-js/blob/master/libraries/botframework-connector/src/auth/appCredentials.ts) from `botframework-connector`, howerver `ExtendedUserTokenProvider` uses [AppCredentials](https://github.com/microsoft/botbuilder-js/blob/master/libraries/botbuilder-core/src/appCredentials.ts) from `botbuilder-core`.

image

## Expected behavior
Give a clear and concise description of what you expected to happen.
The compilation of the botbuilder's packages should work correctly.

## Screenshots
image

## Additional context
These changes are in [master](https://github.com/microsoft/botbuilder-js) and in [4.8](https://github.com/microsoft/botbuilder-js/tree/4.8) branch

[bug]

### PR DESCRIPTION
**Pull request by stevengum**
Fixes #1901

@Batta32

## Specific Changes
  - 
  - loosen Cache requirements in BFHttpClient
  -

### CODE REVIEW

File: libraries/botbuilder/src/botFrameworkAdapter.ts [hunk 1]
```diff
@@ -9,7 +9,7 @@
 import { STATUS_CODES } from 'http';
 import * as os from 'os';
 
-import { Activity, ActivityTypes, BotAdapter, BotCallbackHandlerKey, ChannelAccount, ConversationAccount, ConversationParameters, ConversationReference, ConversationsResult, DeliveryModes, ExpectedReplies, InvokeResponse, ExtendedUserTokenProvider, ResourceResponse, StatusCodes, TokenResponse, TurnContext, INVOKE_RESPONSE_KEY } from 'botbuilder-core';
+import { Activity, ActivityTypes, AppCredentials as CoreAppCredentials, BotAdapter, BotCallbackHandlerKey, ChannelAccount, ConversationAccount, ConversationParameters, ConversationReference, ConversationsResult, DeliveryModes, ExpectedReplies, InvokeResponse, ExtendedUserTokenProvider, ResourceResponse, StatusCodes, TokenResponse, TurnContext, INVOKE_RESPONSE_KEY } from 'botbuilder-core';
```
Comment (christopheranderson) [inline libraries/botbuilder/src/botFrameworkAdapter.ts]: Do a full rename of AppCredentials, not just the alias
